### ISSUE TITLE
Aristois ElytraFlight, Glide on exactly 0.125, and Spider (only when nofall is on) bypass.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#101]
**What server version are you running?**
1.15.2

**What version of NOPE are you running?**
1.6.1

**What is the bug?**
Aristois ElytraFlight, Glide on exactly 0.125, and Spider (only when nofall is on) bypass.

**Please list your plugins below**
NOPE
**Is there anything else to add?**
No.

**Comment by tkn0** [comment]
After a further review on the test server, I believe that my vl level for canceling spider and glide on 0.125 might be a bit high, but ElytraFlight still fully bypasses on my server with little to no alerts.

**Comment by MSWS** [comment]
Please do not combine false negatives in one report. Report each bypass separately. Please also re-open 3 new false positive reports using the new template.
