### ISSUE TITLE
Bypass Template

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#102]
**Is your feature request related to a problem/bug?**
NOPE
**Describe the solution you'd like**
An Bypass issue template
**Have you tried implementing this solution alternatively?**
_Either through the config or separate plugins_
NOPE
**Additional context**
Add any other context or screenshots about the recommendation please put here. This includes if the feature request involves a separate plugin, please make sure to link the plugin.

This will make it tons easier to report bypasses.

**Comment by MSWS** [comment]
This has been added, thanks for the suggestion.
