### ISSUE TITLE
Spend Less time reviewing issues

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#105]
[Ranger](https://github.com/marketplace/ranger) let's you just leave your issues and PRs all one by providing automations, like a merge label that will auto merge when CI tests are done, automatically closes issues that just say Nope is bad, it has too many false without providing any info and you could even use it to stop me from making annoying github app suggest issues.

**Comment by MSWS** [comment]
I don’t want to inflate or unnecessarily add bots. NOPE doesn’t have that many labels nor does it receive that many PRs.
