### ISSUE TITLE
Get Notified when bad code is in a PR. 

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#106]
[Hound](https://github.com/marketplace/hound/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xMDYx) sniffs out bad code in Pull Requests and notify you of the location of the code before the merge. This is like Sonarcloud but more helpful when reviewing PRs.

**Comment by MSWS** [comment]
I don’t want to inflate or unnecessarily add bots. NOPE doesn’t have that many labels nor does it receive that many PRs.
