### ISSUE TITLE
Autofix Code Smells

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#107]
Automatically Fix some of Sonarcloud's code smells (or at least stop more coming via PRs). This is a great app that automatically prevents code smells being introduced by fixing them. [Link](https://github.com/marketplace/codefactor)

**Comment by steviebeenz** [comment]
If you need more customisation, then use [this](https://github.com/marketplace/codelingo)  but be warned, it needs a lot of manual setup.

**Comment by MSWS** [comment]
I don’t want to inflate or unnecessarily add bots. NOPE doesn’t have that many labels nor does it receive that many PRs.
