### ISSUE TITLE
Auto Label PRs

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#108]
[Link](https://github.com/marketplace/auto-badge) . This amazing Bot automatically labels Pull Requests so you don't have to. It works well with the Ranger bot I suggested earlier as ranger can automatically assign you etc. to specific types of PRs.

**Comment by MSWS** [comment]
I don’t want to inflate or unnecessarily add bots. NOPE doesn’t have that many labels nor does it receive that many PRs.
