### ISSUE TITLE
Custom aliases.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#109]
**Is your feature request related to a problem/bug?**
No.

**Describe the solution you'd like**
The feature to specify custom aliases or a custom main command in the config.
Ex: https://hatebin.com/grinffimub

**Have you tried implementing this solution alternatively?**
No, I know it can be done with other plugins but it seems a bit excessive.

**Additional context**
None.

**Comment by MSWS** [comment]
I will not be adding this for now. You can easily configure a command alias without plugins by creating one in the commands.yml file.
