### ISSUE TITLE
So many false positives

### ISSUE THREAD

**Issue by Nximus** [MSWS/NOPE#113]
I was having a player simply test out whether or not they could receive an item from stepping on a pressure plate connected to a command block. They got flagged for HighCPS when they stepped on the pressure plate and then auto-banned from it. They also were being flagged for Killaura when hitting and killing pigs normally. They had no hacked client or any cheats enabled. This was their first time ever playing Minecraft.

**Comment by MSWS** [comment]
What was the command in the command block? Have you checked out the false flag template?

**Comment by Nximus** [comment]
It was /Minecraft:give @p diamond 1
My intent was to use it at the end of a parkour course. What is the false flag template?

**Comment by steviebeenz** [comment]
The false flag template is the False Flag button when you click new issue.

**Comment by Nximus** [comment]
That option wasn't presented when I submitted the report initially and I'm not sure why.

**Comment by MSWS** [comment]
Please re open an issue using the proper format.
