### ISSUE TITLE
Ice false flags speed 3.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#117]
**What server version are you running?**
Paper 1.15.2

**What Minecraft Client Version are you running?**
Vanilla 1.15.2
**What version of NOPE are you running?**
1.6.1
**What is the debug ID?**
Speed#3

**Is there any debug information? (Please include average info if available)**
0.59>0.55

**What is causing this false positive?**
Running on ice.

**Is this false positive reproducible on the test server?**
Probably, idk how to get ice on the test server.

**Please list all your server plugins**
Griefprevention, tradeshops, and a lot of text modifying plugins.
**Is there anything else to add?**
nope

**Comment by MSWS** [comment]
This should be patched in 1.6.2.

**Comment by MSWS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Speed#3 + ice](https://trello.com/c/gHPOiQ7H/163-speed3-ice)
