### ISSUE TITLE
Cancel does not seem to work when the player is jumping around.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#118]
**What server version are you running?**
Paper 1.15.2

**What version of NOPE are you running?**
1.6.1

**What is the bug?**
When using speed/bhop if the player is holding spacebar the cancel command does not seem to teleport them back as well as it does when they are not jumping,
https://gyazo.com/548e797544197d9cd1f2a16dfffc6872
**Please list your plugins below**
Griefprevention/tradeshops and some chat/text managing plugins
**Is there anything else to add?**
Nope

**Comment by tkn0** [comment]
It appears that this only happens for speed when speed#3 is turned off; however, speed#3 currently falses players on ice, and ice travel is a huge part of survival gameplay!

**Comment by MSWS** [comment]
Speed will be patched, however this isn't a bug then. In future reports please make sure you include if you've disabled/otherwise modified NOPE's config.
