### ISSUE TITLE
Aristois ElytraFlight Bypass

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#119]
**What server version are you running?**
Paper 1.15.2

**What Minecraft Client are you running?**
Aristois 1.15.2 Latest

**What version of NOPE are you running?**
1.6.1

**What is causing this false negative?**
ElytraFlight with aristois allows the user to fly up and down without rockets and no restrictions.

**Is this false-negative reproducible on the test server?**
I am unsure as I cannot obtain an elytra.
**Please list all your plugins on the server**
Grief Prevention, TradeShop, Text/Formatting Plugins
**Is there anything else to add?**
No.

**Comment by MSWS** [comment]
ElytraFlight is a difficult hack to flag due to how velocity works, I will look into adding a new check.

**Comment by tkn0** [comment]
Yeah, I noticed all the flying seemed normal, just that the user could go up infinitely while holding space.
