### ISSUE TITLE
Nope Broken

### ISSUE THREAD

**Issue by coolpvpv1** [MSWS/NOPE#12]
What server version are you running?
Spigot 1.8.8

What version of NOPE are you running?
1.2.1

What is the bug?
i just put it on my 1.8.8 server with protocollib do /nope it just says /nope in chat it doesn't detect anything deoped myself etc etc still nothing was working

Is there anything else to add?
no?

**Comment by d-513** [comment]
i am having the same issue.

**Comment by d-513** [comment]
closing without a comment?

**Comment by MSWS** [comment]
NOPE has undergone a substantial re-write. If the issue is still ocurring on servers 1.13+ please create a new issue.
