### ISSUE TITLE
NoFall False positive 3 blocks

### ISSUE THREAD

**Issue by ghost** [MSWS/NOPE#120]
**What server version are you running?**
Paper Spigot 1.15.2

**What Minecraft Client Version are you running?**
Vanilla 1.15.2

**What version of NOPE are you running?**
1.6.1

**What is the debug ID?**
NoFall#1
**Is there any debug information? (Please include average info if available)**
Expected: 0.580
Receive: 0.000

**What is causing this false positive?**
Jumping 3 blocks down. Normally will not cause any damage.

**Is this false positive reproducible on the test server?**
yes

**Please list all your server plugins**
Only NOPE

**Is there anything else to add?**
It seem to happen on every server I tried.

**Comment by MSWS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NoFall false flag 3 blocks high](https://trello.com/c/wWZvrceL/164-nofall-false-flag-3-blocks-high)

**Comment by MSWS** [comment]
Thanks for reporting, should be fixed in 1.6.2.
