### ISSUE TITLE
More Custom Flags

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#122]
**Is your feature request related to a problem/bug?**
No.
**Describe the solution you'd like**
I would like to be able to set custom command lines for specific flags.
Ex. Instead of (Speed: - command line) you could do (Speed#2: - command line) in the config. 
**Have you tried implementing this solution alternatively?**
No.

**Additional context**
None.

**Comment by MSWS** [comment]
This has been added and will be included in 1.6.2.

**Comment by MSWS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Debug level actions](https://trello.com/c/QjjJ98kb/165-debug-level-actions)
