### ISSUE TITLE
Less Lag

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#124]
**Is your feature request related to a problem/bug?**

Yes, my server crashes due to lag. 

**Describe the solution you'd like**
Enhance the plugins code to make it more performant, it was doing 20% of tick. 

**Have you tried implementing this solution alternatively?**
_Either through the config or separate plugins_
Yeah, ClearLag/LaggRemover and AFK Kick helps... 

**Additional context**
Add any other context or screenshots about the recommendation please put here. This includes if the feature request involves a separate plugin, please make sure to link the plugin.

I am using 1.6.1
I am not linking to these plugins because all they do is run Garbage Collection, Clear Entities (namely ground items)

**Comment by steviebeenz** [comment]
@MSWS IDK if this is possible to fix, I might just have to upgrade my server...

**Comment by MSWS** [comment]
Please run a timings report and post the link.

**Comment by MSWS** [comment]
This will be handled in DMs.
