### ISSUE TITLE
Kill Aura False Positive with Shulker

### ISSUE THREAD

**Issue by DumplingSaint** [MSWS/NOPE#126]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
MC 1.15.2 Paper-327
**What Minecraft Client Version are you running?**
1.15.2
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.6.2
**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_

**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_

**What is causing this false positive?**
_What exactly are you doing that causes a false positive?_
Jumping up and down on top of a shulker while hitting it.

**Is this false positive reproducible on the test server?**
_MSWS.xyz is the IP_

**Please list all your server plugins**

**Is there anything else to add?**

**Comment by MSWS** [comment]
Confirmed this does occur and am currently looking into patching it.

**Comment by MSWS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [KA + Shulkers](https://trello.com/c/lIx6zI8U/171-ka-shulkers)

**Comment by MSWS** [comment]
This should be fixed in 1.6.3.
