### ISSUE TITLE
Kill Aura crash

### ISSUE THREAD

**Issue by DumplingSaint** [MSWS/NOPE#127]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.15.2 Paper-332 

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.6.2

**What is the bug?**
_Please be descriptive_
Server Crash

**Please list your plugins below**
https://gyazo.com/ed4d1c181dab48cc98b2c97f1949c568

**Is there anything else to add?**
_Are there any error logs?_
>.... [16:19:30 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-332 (MC: 1.15.2) ---
>.... [16:19:30 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [16:19:30 ERROR]: ------------------------------
>.... [16:19:30 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [16:19:30 ERROR]: ------------------------------
>.... [16:19:30 ERROR]: Current Thread: Server thread
>.... [16:19:30 ERROR]: PID: 18 | Suspended: false | Native: false | State: RUNNABLE
>.... [16:19:30 ERROR]: Stack:
>.... [16:19:30 ERROR]: java.util.AbstractCollection.toArray(AbstractCollection.java:139)
>.... [16:19:30 ERROR]: java.util.ArrayList.<init>(ArrayList.java:178)
>.... [16:19:30 ERROR]: org.bukkit.craftbukkit.v1_15_R1.CraftServer.getWorlds(CraftServer.java:704)
>.... [16:19:30 ERROR]: org.bukkit.Bukkit.getWorlds(Bukkit.java:533)
>.... [16:19:30 ERROR]: xyz.msws.nope.modules.npc.NPC.<init>(NPC.java:74)
>.... [16:19:30 ERROR]: xyz.msws.nope.modules.npc.NPCModule.getOrSpawn(NPCModule.java:89)
>.... [16:19:30 ERROR]: xyz.msws.nope.checks.combat.killaura.KillAura3.spawnNPC(KillAura3.java:167)
>.... [16:19:30 ERROR]: xyz.msws.nope.checks.combat.killaura.KillAura3.onDamage(KillAura3.java:152)
>.... [16:19:30 ERROR]: com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor628.execute(Unknown Source)
>.... [16:19:30 ERROR]: org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [16:19:30 ERROR]: org.bukkit.plugin.EventExecutor$$Lambda$2282/2050652304.execute(Unknown Source)
>.... [16:19:30 ERROR]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [16:19:30 ERROR]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [16:19:30 ERROR]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [16:19:30 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240)
>.... [16:19:30 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1008)
>.... [16:19:30 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:895)
>.... [16:19:30 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:851)
>.... [16:19:30 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1040)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.EntityShulker.damageEntity(EntityShulker.java:377)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1741)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2096)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$5071/1976091909.run(Unknown Source)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051)
>.... [16:19:30 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966)
>.... [16:19:30 ERROR]: java.lang.Thread.run(Thread.java:748)

**Comment by MSWS** [comment]
I will look into these, thanks!

**Comment by MSWS** [comment]
This should be patched in the next update.

**Comment by MSWS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [KA Crash](https://trello.com/c/EYxlid8E/169-ka-crash)
