### ISSUE TITLE
Speed#4 and boats.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#128]
**What server version are you running?**
1.15.2 Paper

**What Minecraft Client Version are you running?**
1.15.2 Vanilla
**What version of NOPE are you running?**
1.6.1
**What is the debug ID?**
Not sure.

**Is there any debug information? (Please include average info if available)**
No sure.

**What is causing this false positive?**
Players set off insane VL alerts with boats (getting in and out) if they are a bit laggy when speed 4 and sometimes bhop is on.

**Is this false positive reproducible on the test server?**
I cannot gather items on the test server as when I break blocks nothing happens.

**Please list all your server plugins**
GriefPrevention, Tradeshops.
**Is there anything else to add?**
I will update this later on with more evidence when I have time to test the AC

**Comment by deralmas** [comment]
Can confirm. Happens to mee too

**Comment by MSWS** [comment]
This should be patched in 1.6.3.
