### ISSUE TITLE
Wrongful Bans - Advised to submit from our dev (trialing your anti cheat)

### ISSUE THREAD

**Issue by Elijahzeal** [MSWS/NOPE#130]
**What server version are you running?**
Bukkit / Paper 1.15.2

**What version of NOPE are you running?**
Nope 1.6.1 / Online Version 1.6.2

**What is the bug?**
Wrongful bans

**Please list your plugins below**
-Why's this bit needed out of curiosity? - It's not being effected by any of the other plugins that we have.
**Is there anything else to add?**
Are there any error logs? 
- No error logs. Plugin is just triggering automatically from players who have no additional clients. Slow_Falling from shulkers automatically triggers Glide/Fly/Speed(all numbers) and bans upon so. This needs a lil fix.
- Had to temporarily disable the plugin.

**Comment by MSWS** [comment]
These are called False Positives and I rely on the people that use NOPE to report false positives. I cannot unfortunately cover every edge case, I have been made aware of shulkers and I will look into them.

**Comment by Elijahzeal** [comment]
No worries, didn't know the bracket that the issue came under, so my bad. Is there anything that I can do atm that may allow me to log the actions but not ban? Appreciate you looking into shulkers as well :) Looking forward to the next update on the plugin to reinstall it again and report anything else.

**Comment by MSWS** [comment]
Yes, you can configure what actions NOPE takes by changing the config. The wiki goes into depth about this, basically the log action will log things without kicking/banning.

**Comment by Elijahzeal** [comment]
Cheers :D
