### ISSUE TITLE
Pom.xml contains dependencies that point to a file in a local filesystem

### ISSUE THREAD

**Issue by deralmas** [MSWS/NOPE#131]
The lines [here](https://github.com/MSWS/NOPE/blob/14d4fd08856d56da99441eb745bcd39e71050212/dependency-reduced-pom.xml#L140), [here](https://github.com/MSWS/NOPE/blob/14d4fd08856d56da99441eb745bcd39e71050212/dependency-reduced-pom.xml#L147) and [here](https://github.com/MSWS/NOPE/blob/14d4fd08856d56da99441eb745bcd39e71050212/dependency-reduced-pom.xml#L154) point to file in a local filesystem, not allowing compilation for other users without manually downloading the dependencies and changing their respecting lines.

**Comment by MSWS** [comment]
How do you suggest I fix this? The dependencies listed aren't hosted on maven afaik.

**Comment by deralmas** [comment]
I'll research a bit about their availability online. I don't know if it's possible, but couldn't you make them optional?

**Comment by MSWS** [comment]
NOPE uses each dependency as part of its classes (ban hooks and compatabilities). So I don’t think it’s possible.

**Comment by deralmas** [comment]
It seems that Advanced Ban is using [Github's package system](https://github.com/DevLeoko/AdvancedBan/packages/147493), so it's actually hosted somewhere.

**Comment by deralmas** [comment]
I can't trace down the version of MaxBans you're using, as there are [multiple](https://github.com/netherfoam/MaxBans) [versions](https://github.com/netherfoam/MaxBans-Plus) available and neither of them are on version 1.0, but badbones69 hosts [CrazyEnchantments](https://github.com/badbones69/Crazy-Enchantments) on his/her [maven repository](https://nexus.badbones69.com/repository/maven-releases/) and adding it seems pretty easy. Citing Crazy-Enchantments's [repository description](https://github.com/badbones69/Crazy-Enchantments/blob/v1.8/README.md):
> Maven:
```xml
<repository>
    <id>nexus</id>
    <url>https://nexus.badbones69.com/repository/maven-releases/</url>
</repository>

<dependency>
    <groupId>me.badbones69</groupId>
    <artifactId>crazyenchantments-plugin</artifactId>
    <version>{Latest Version}</version>
</dependency>
```

**Comment by MSWS** [comment]
Looks promising, any idea for the others?

**Comment by deralmas** [comment]
Advanced Ban's way of managing packages is pretty bad imho, requiring the creation of a github account and some configuring here and there just for downloading from its repository.
Could you tell me where you downloaded MaxBans?

**Comment by MSWS** [comment]
https://dev.bukkit.org/projects/maxbans

**Comment by MSWS** [comment]
I've added CrazyEnchants dependency for now. If you find repositories for any other system scoped dependencies please let me know.
