### ISSUE TITLE
Fast Break #1 with SilkSpawner Plugin

### ISSUE THREAD

**Issue by Rend-Creator** [MSWS/NOPE#132]
**What server version are you running?**
Paper 1.15.2 Build 353

**What Minecraft Client Version are you running?**
1.15.2

**What version of NOPE are you running?**
1.6.2

**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_
No Info.

**Is there any debug information? (Please include average info if available)**
No Info.

**What is causing this false positive?**
Whenever a player break a spawner with the No Permission of the SilkSpawners Plugin, the player is severely get flagged with Fast Break#1. 

**Is this false positive reproducible on the test server?**
Haven't tested yet.

**Please list all your server plugins**
- Nope 1.6.2
- SilkSpawners 6.2.0 

**Is there anything else to add?**
I'll update this report ticket if I got anything new about the issue.

**Comment by MSWS** [comment]
Does this happen without silksspawners?

**Comment by Rend-Creator** [comment]
No, only with silk spawners included. Specifically when you have No Permissions of having a mined spawner. In addition, the false positive also appears on MineableSpawners Plugin. I've just this now recently.

The false positive goes away if I granted the player with permission of mining the spawner with pickaxe + silk touch

**Comment by MSWS** [comment]
Interesting, can you tell me what the exact behavior of the spawner is when the player doesn't have the permission? Like a video of what happens when the player tries to mine the spawner?

**Comment by Rend-Creator** [comment]
Okay I'll create a video example later. I'll also turn on the debug mode to see the in depth stuff.

**Comment by MSWS** [comment]
I was able to reproduce this false positive without silk spawners, this should be patched in 1.6.3.
