### ISSUE TITLE
Snakeyaml crash and something else.

### ISSUE THREAD

**Issue by DumplingSaint** [MSWS/NOPE#133]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.15.2 Paper-332
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.6.2
**What is the bug?**
_Please be descriptive_
Server randomly crashes because of nope.
**Please list your plugins below**
https://gyazo.com/ed4d1c181dab48cc98b2c97f1949c568
**Is there anything else to add?**
_Are there any error logs?_

I have three

.... [22:29:52 INFO]: CraftedMuffin issued server command: //br sphere 20%18:3,20%18:0,60%0 1
>.... [22:30:06 INFO]: -=Builder=- CraftedMuffin t
>.... [22:30:18 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-354 (MC: 1.15.2) ---
>.... [22:30:18 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [22:30:18 ERROR]: ------------------------------
>.... [22:30:18 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [22:30:18 ERROR]: ------------------------------
>.... [22:30:18 ERROR]: Current Thread: Server thread
>.... [22:30:18 ERROR]: PID: 18 | Suspended: false | Native: false | State: RUNNABLE
>.... [22:30:18 ERROR]: Stack:
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.reader.StreamReader.prefixForward(StreamReader.java:162)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.scanner.ScannerImpl.scanPlain(ScannerImpl.java:2012)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.scanner.ScannerImpl.fetchPlain(ScannerImpl.java:1044)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:399)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
>.... [22:30:18 ERROR]: org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
>.... [22:30:18 ERROR]: org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
>.... [22:30:18 ERROR]: org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
>.... [22:30:18 ERROR]: org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
>.... [22:30:18 ERROR]: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183)
>.... [22:30:18 ERROR]: xyz.msws.nope.modules.data.CPlayer.<init>(CPlayer.java:74)
>.... [22:30:18 ERROR]: xyz.msws.nope.modules.data.PlayerManager.getPlayer(PlayerManager.java:45)
>.... [22:30:18 ERROR]: xyz.msws.nope.NOPE.getCPlayer(NOPE.java:432)
>.... [22:30:18 ERROR]: xyz.msws.nope.checks.combat.AutoClicker1.onInteract(AutoClicker1.java:57)
>.... [22:30:18 ERROR]: com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor657.execute(Unknown Source)
>.... [22:30:18 ERROR]: org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [22:30:18 ERROR]: org.bukkit.plugin.EventExecutor$$Lambda$2285/1182285645.execute(Unknown Source)
>.... [22:30:18 ERROR]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [22:30:18 ERROR]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [22:30:18 ERROR]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [22:30:18 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471)
>.... [22:30:18 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:143)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1360)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4951/684820478.run(Unknown Source)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1232)
>.... [22:30:18 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
>.... [22:30:18 ERROR]: java.lang.Thread.run(Thread.java:748)

second crash

.... [22:24:54 WARN]: Can't keep up! Is the server overloaded? Running 5424ms or 108 ticks behind
>.... [22:24:55 INFO]: ItsRubySteve issued server command: /hdb search fnaf ar
>.... [22:25:06 INFO]: ItsRubySteve issued server command: /hdb search fnaf
>.... [22:25:13 INFO]: ItsRubySteve issued server command: /hdb search fnaf ar
>.... [22:25:17 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-354 (MC: 1.15.2) ---
>.... [22:25:17 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [22:25:17 ERROR]: ------------------------------
>.... [22:25:17 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [22:25:17 ERROR]: ------------------------------
>.... [22:25:17 ERROR]: Current Thread: Server thread
>.... [22:25:17 ERROR]: PID: 18 | Suspended: false | Native: false | State: RUNNABLE
>.... [22:25:17 ERROR]: Stack:
>.... [22:25:17 ERROR]: java.lang.Throwable.fillInStackTrace(Native Method)
>.... [22:25:17 ERROR]: java.lang.Throwable.fillInStackTrace(Throwable.java:784)
>.... [22:25:17 ERROR]: java.lang.Throwable.<init>(Throwable.java:251)
>.... [22:25:17 ERROR]: java.lang.Exception.<init>(Exception.java:54)
>.... [22:25:17 ERROR]: java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:44)
>.... [22:25:17 ERROR]: java.lang.InstantiationException.<init>(InstantiationException.java:53)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.newInstance(BaseConstructor.java:325)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.newInstance(BaseConstructor.java:294)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.newMap(BaseConstructor.java:349)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:445)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521)
>.... [22:25:17 ERROR]: org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:164)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:148)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
>.... [22:25:17 ERROR]: org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
>.... [22:25:17 ERROR]: org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
>.... [22:25:17 ERROR]: org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
>.... [22:25:17 ERROR]: org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
>.... [22:25:17 ERROR]: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183)
>.... [22:25:17 ERROR]: xyz.msws.nope.modules.data.CPlayer.<init>(CPlayer.java:74)
>.... [22:25:17 ERROR]: xyz.msws.nope.modules.data.PlayerManager.getPlayer(PlayerManager.java:45)
>.... [22:25:17 ERROR]: xyz.msws.nope.NOPE.getCPlayer(NOPE.java:432)
>.... [22:25:17 ERROR]: xyz.msws.nope.checks.combat.AutoClicker1.onInteract(AutoClicker1.java:57)
>.... [22:25:17 ERROR]: com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor657.execute(Unknown Source)
>.... [22:25:17 ERROR]: org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [22:25:17 ERROR]: org.bukkit.plugin.EventExecutor$$Lambda$2285/1182285645.execute(Unknown Source)
>.... [22:25:17 ERROR]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [22:25:17 ERROR]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [22:25:17 ERROR]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [22:25:17 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471)
>.... [22:25:17 ERROR]: org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:143)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1360)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4951/684820478.run(Unknown Source)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1232)
>.... [22:25:17 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
>.... [22:25:17 ERROR]: java.lang.Thread.run(Thread.java:748)

third

>.... [21:17:53 INFO]: -=Verified Builder=- andrejklol David624 is thare a way to get nps
>.... [21:18:02 INFO]: -=Verified Builder=- young1 get op
>.... [21:18:15 INFO]: -=Verified Builder=- andrejklol oof
>.... [21:18:19 INFO]: young1 issued server command: /plot visit andrejklol
>.... [21:18:31 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-354 (MC: 1.15.2) ---
>.... [21:18:31 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [21:18:31 ERROR]: ------------------------------
>.... [21:18:31 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [21:18:31 ERROR]: ------------------------------
>.... [21:18:31 ERROR]: Current Thread: Server thread
>.... [21:18:31 ERROR]: PID: 18 | Suspended: false | Native: false | State: RUNNABLE
>.... [21:18:31 ERROR]: Stack:
>.... [21:18:31 ERROR]: java.util.AbstractCollection.toArray(AbstractCollection.java:143)
>.... [21:18:31 ERROR]: java.util.ArrayList.<init>(ArrayList.java:178)
>.... [21:18:31 ERROR]: org.bukkit.craftbukkit.v1_15_R1.CraftServer.getWorlds(CraftServer.java:704)
>.... [21:18:31 ERROR]: org.bukkit.Bukkit.getWorlds(Bukkit.java:533)
>.... [21:18:31 ERROR]: xyz.msws.nope.modules.npc.NPC.<init>(NPC.java:74)
>.... [21:18:31 ERROR]: xyz.msws.nope.checks.packet.PlayerESP1.spawnNPCs(PlayerESP1.java:144)
>.... [21:18:31 ERROR]: xyz.msws.nope.checks.packet.PlayerESP1.onGamemode(PlayerESP1.java:120)
>.... [21:18:31 ERROR]: com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor666.execute(Unknown Source)
>.... [21:18:31 ERROR]: org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [21:18:31 ERROR]: org.bukkit.plugin.EventExecutor$$Lambda$2276/828966440.execute(Unknown Source)
>.... [21:18:31 ERROR]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [21:18:31 ERROR]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [21:18:31 ERROR]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [21:18:31 ERROR]: net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:1545)
>.... [21:18:31 ERROR]: org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:1028)
>.... [21:18:31 ERROR]: com.buildersrefuge.utilities.object.NoClipManager.checkForBlocks(NoClipManager.java:46)
>.... [21:18:31 ERROR]: com.buildersrefuge.utilities.object.NoClipManager$$Lambda$4002/1196098496.run(Unknown Source)
>.... [21:18:31 ERROR]: org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
>.... [21:18:31 ERROR]: org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [21:18:31 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
>.... [21:18:31 ERROR]: net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
>.... [21:18:31 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
>.... [21:18:31 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
>.... [21:18:31 ERROR]: java.lang.Thread.run(Thread.java:748)

**Comment by MSWS** [comment]
Not entirely sure what's causing this. If this persists in the next update please do let me know.
