### ISSUE TITLE
AFK Fishing Detected as HighCPS

### ISSUE THREAD

**Issue by alqassam1998** [MSWS/NOPE#134]
**What server version are you running?**
Paper 1.15.2 Latest Build

**What Minecraft Client Version are you running?**
1.15.2

**What version of NOPE are you running?**
1.6.1

**What is the debug ID?**
HighCPS#3, HighCPS#2, HighCPS#1

**Is there any debug information? (Please include average info if available)**
N/A

**What is causing this false positive?**
AFK fishing and catching fish quickly.

**Is this false positive reproducible on the test server?**
Not tested.

**Please list all your server plugins**
https://imgur.com/2nU0tV4

**Is there anything else to add?**
I've disabled HighCPS and haven't done debugging.

**Comment by MSWS** [comment]
Thanks for the report, I will fix this in the next update.

**Comment by MSWS** [comment]
I was unable to replicate this using this fish farm:
https://i.ytimg.com/vi/CSOdAqIGcwM/maxresdefault.jpg

Please provide more details if this is still occuring.
