### ISSUE TITLE
Banwave countdown goes negative

### ISSUE THREAD

**Issue by DumplingSaint** [MSWS/NOPE#137]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.5.2 Paper 332
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.6.3
**What is the bug?**
_Please be descriptive_
https://gyazo.com/4361f261dbbe292f1bc8c8fe4fe69528
**Please list your plugins below**
https://gyazo.com/ed4d1c181dab48cc98b2c97f1949c568
**Is there anything else to add?**
_Are there any error logs?_

**Comment by DumplingSaint** [comment]
It eventually does go back to positives. Just takes a while of being in the negatives. Scoreboard as a whole doesn't seem to work since 1.6.3.

**Comment by steviebeenz** [comment]
Having Same Issue.

**Comment by MSWS** [comment]
Should be fixed in 1.6.4.
