### ISSUE TITLE
Fake positive NOPE AntiCheat 1.2.3

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#14]
**What server version are you running?**
1.15.2

**What version of NOPE are you running?**
1.2.3

**What is the bug?**
When a player jump, i have allert of step, if a player fly with gamemode 1 or other he use "spider", if player break a block he use "Fastbreak" and sometimes when he sprint "SafeWalk"

**Is there anything else to add?**
Can you add support 1.9.4, because in France this version is often used thanks to the Pactify launcher. And a lot of server use the 1.9.4 :) Like mine ;)

**Comment by MSWS** [comment]
I will look into these, thank you.

**Comment by Neiy0** [comment]
Thanks you, sorry for my bad english. 

If I meet other false positives, I report them to you! :) Delighted that you resume the development of this plugin because good, another also did it https://www.spigotmc.org/resources/ness-anti-cheat-reloaded.75887/

**Comment by Neiy0** [comment]
And if you can fix it, 
![erre](https://user-images.githubusercontent.com/39565971/81167748-0c277400-8f96-11ea-9217-a00f72f5be36.PNG)

**Comment by Neiy0** [comment]
![weard](https://user-images.githubusercontent.com/39565971/81167849-3bd67c00-8f96-11ea-8473-6e8c519844a9.PNG)
He work sometimes, weird.

**Comment by MSWS** [comment]
All of the issues you listed should now be patched in 1.2.4.

**Comment by Neiy0** [comment]
Even the 1.9.4 support?

**Comment by MSWS** [comment]
Not necessarily the 1.9.4 support, though NOPE might already be compatible .

**Comment by Neiy0** [comment]
So I can use it in 1.9.4?

**Comment by MSWS** [comment]
> So I can use it in 1.9.4?

I’m saying it may or may not work. I have not tested I and it is not explicitly supported.

**Comment by Neiy0** [comment]
Okay, and if it works half-heartedly, can you make it fully compatible?

**Comment by MSWS** [comment]
> Okay, and if it works half-heartedly, can you make it fully compatible?

You are free to report any issues, I may or may not fix them if they are on an unsupported version.

**Comment by Neiy0** [comment]
Okey, thanks you ! :)
