### ISSUE TITLE
InventoryMove on Impact

### ISSUE THREAD

**Issue by lokka30** [MSWS/NOPE#140]
**What server version are you running?**
Paper v362 1.15.2

**What Minecraft Client are you running?**
Impact 1.15.2

**What version of NOPE are you running?**
1.6.3

**What is causing this false negative?**
InventoryMove isn't being flagged. I can open my inventory and move at the same time with WASD keys.

**Is this false negative reproducible on the test server?**
I have done this on my own test server with a bone stock config, so I assume so. Don't have the time as of writing this to launch it and test.

**Please list all your plugins on the server**
NOPE, ProtocolLib, WorldEdit

**Is there anything else to add?**
Nope :)

**Comment by MSWS** [comment]
This will be worked on in the future however for now it is a low priority.

**Comment by lokka30** [comment]
No problem at all. Thanks a lot MSWS, really appreciate your work on this anticheat!

**Comment by steviebeenz** [comment]
Hmm... With my custom client I could achieve this by simple closing and reopening the inventory.
Potentially prevent inventory items moving while it's closed? This would also block autosoup...

**Comment by MSWS** [comment]
> Hmm... With my custom client I could achieve this by simple closing and reopening the inventory.
> 
> Potentially prevent inventory items moving while it's closed? This would also block autosoup... 

There is no way of detecting when the clients inventory is open or closed, otherwise this would be a very simple flag to check.

**Comment by steviebeenz** [comment]
https://www.spigotmc.org/threads/inventory-close-event.126456/
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryOpenEvent.html

You could use these to track if the inv is open....
