### ISSUE TITLE
Placing on ladder flags autobuild and scaffold

### ISSUE THREAD

**Issue by zihasz** [MSWS/NOPE#142]
**What server version are you running?**
Waterfall, 1.15.2 Paper

**What Minecraft Client Version are you running?**
Sigma5 1.15.2 JelloPortal

**What version of NOPE are you running?**
1.6.3

**What is the debug ID?**
AutoBuild#1, Scaffold#2

**Is there any debug information? (Please include average info if available)**
Scaffold: Diff. ~55 > 30
AutoBuild: Dist. 4

**What is causing this false positive?**
Placing a block an a ladder while climbing

**Is this false positive reproducible on the test server?**
Yes, I found it on there.

**Please list all your server plugins**
???

**Is there anything else to add?**
No

**Comment by MSWS** [comment]
Thanks for reporting I will look into this.

**Comment by MSWS** [comment]
Should be fixed in 1.7,
