### ISSUE TITLE
No InvMove and Rare NCP Speed flags

### ISSUE THREAD

**Issue by zihasz** [MSWS/NOPE#143]
**What server version are you running?**
1.15.2 Paper

**What Minecraft Client are you running?**
Sigma5 1.15 JelloPortal

**What version of NOPE are you running?**
1.6.3

**What is causing this false negative?**
No flags for InvMove, rarely flags for NCP Speed

**Is this false negative reproducible on the test server?**
Yes.

**Please list all your plugins on the server**
Done it on the test server

**Is there anything else to add?**
NOPE

**Comment by MSWS** [comment]
Speed checks are a low priority atm, thanks for reporting.
