### ISSUE TITLE
1.16.1 Support

### ISSUE THREAD

**Issue by SudoPigeon223** [MSWS/NOPE#145]
This isn't really a issue but Spigot just released 1.16.1 server software meaning that lots of servers are going to be updating soon. It would be great to have 1.16.1 support for NOPE.

**Comment by MSWS** [comment]
I will look into 1.16.1 however it probably won’t be added for a while.

**Comment by steviebeenz** [comment]
@MSWS All 1.16 code works on 1.16.1, 1.16.1 is a Realms bug fix. You just need to modify the plugin.yml

**Comment by SudoPigeon223** [comment]
I tried it on 1.16.1 Spigot and it flipped and wouldn't let me move.

**Comment by steviebeenz** [comment]
Yeah that's coz it doesn't fully support 1.16 yet 😜

**Comment by tkn0** [comment]
Could someone ping me on discord when 1.16.1 is fully supported :)

**Comment by MSWS** [comment]
Forgot to close this, 1.16.1 should be supported in 1.7.
