### ISSUE TITLE
Flight#1 and Slime Blocks

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#146]
**What server version are you running?**
1.15.2 Paper
**What Minecraft Client Version are you running?**
1.15.2 Vanilla
**What version of NOPE are you running?**
1.6.3

**What is the debug ID?**
Flight#1
**Is there any debug information? (Please include average info if available)**
Nope.

**What is causing this false positive?**
Standing/moving on slime or doing something with slime blocks.

**Is this false positive reproducible on the test server?**
Probably.

**Please list all your server plugins**
Nothing to change ac
**Is there anything else to add?**
Nope.

**Comment by MSWS** [comment]
Was unable to replicate. Please add more detail/video if this issue is still occuring.
