### ISSUE TITLE
Test Server

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#148]
**Is your feature request related to a problem/bug?**
Yes

**Describe the solution you'd like**
So on the test server, say it's a slime block bug, but you haven't advanced enough on it to get slime blocks, so you can't test it there. 
Potentially you could let people change gamemode and install a plot plugin like PLOTSQUARED. 

**Have you tried implementing this solution alternatively?**
_Either through the config or separate plugins_
No, I don't have perms xD. 

**Additional context**
Add any other context or screenshots about the recommendation please put here. This includes if the feature request involves a separate plugin, please make sure to link the plugin.
https://github.com/IntellectualSites/PlotSquared/ (Build from source or pay $7)

**Comment by tkn0** [comment]
We need this ^

**Comment by steviebeenz** [comment]
@MSWS is this coming?

**Comment by MSWS** [comment]
I've gone ahead and given creative mode permissions to everyone by default. If this is abused they will be removed.

**Comment by steviebeenz** [comment]
@MSWS do we also have perms to go back to gamemode 0?

**Comment by MSWS** [comment]
Yes

**Comment by steviebeenz** [comment]
@MSWS I think you might want to add some simple rules like only creative for getting items to test, and reset the world often? Automate this with MvC

**Comment by MSWS** [comment]
The index out of bounds thing is ProtocolLib I believe.
