### ISSUE TITLE
Speed#4 ????

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#149]
**What server version are you running?**
Paper 1.15.2
**What Minecraft Client Version are you running?**
1.15.2 Vanilla
**What version of NOPE are you running?**
1.6.3
**What is the debug ID?**
Speed#4
**Is there any debug information? (Please include average info if available)**
I lost the info
**What is causing this false positive?**
I think it is related to swimming as I will get an alert for a VL of around 4000 and then when I go to spectate the player just seems to be swimming normally.
**Is this false positive reproducible on the test server?**
I have not tried.
**Please list all your server plugins**
None to affect ac
**Is there anything else to add?**
nope

**Comment by tkn0** [comment]
This seems to be with all speeds and it is with players walking under/in water with depth strider

**Comment by tkn0** [comment]
The depth strider is with speed#3

**Comment by MSWS** [comment]
Unable to replicate, please add more detail/video if this is still occurring.
