### ISSUE TITLE
Console error when hitting entity

### ISSUE THREAD

**Issue by nice0day** [MSWS/NOPE#15]
**What server version are you running?**
1.15.2

**What version of NOPE are you running?**
1.2.3

**What is the bug?**
When i hit a mob or an entity i get errors in console

https://pastebin.com/rx2z5ypX

**Comment by MSWS** [comment]
Thank you, I will look into this.

**Comment by MSWS** [comment]
This should be fixed in the next update (v1.2.4).

**Comment by MSWS** [comment]
1.2.4 is now released.
