### ISSUE TITLE
InventoryClickEvent Cancel bug

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#150]
**What server version are you running?**
1.15.2
**What version of NOPE are you running?**
Nope 1.6.3
**What is the bug?**
The event is still canceled when I leave the GUI if I had gone past the main menu.
**Please list your plugins below**
None to affect this bug.i
**Is there anything else to add?**
I had a similar issue and I fixed it by adding these two lines:
I don't know if this is the best way as I am a novice with java.
https://hatebin.com/deilvpqdsf

**Comment by MSWS** [comment]
I'm removing the inventory for now, it might get revisited later and improved.
