### ISSUE TITLE
Elytra Takeoffs and noslowdown

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#151]
**What server version are you running?**
Paper Spigot 1.15.2
**What Minecraft Client Version are you running?**
Vanilla 1.15.2
**What version of NOPE are you running?**
1.6.3
**What is the debug ID?**
NoSlowDown 4
**Is there any debug information? (Please include average info if available)**
Unsure
**What is causing this false positive?**
Elytra takeoffs seem to flag no slowdown due to the initial velocity
**Is this false positive reproducible on the test server?**
idk
**Please list all your server plugins**
none applicable to the bug

**Comment by MSWS** [comment]
Unable to replicate false positive, please report more details or provide video.
