### ISSUE TITLE
Autoclicker checks/Feature req/Bug

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#156]
**What server version are you running?**
1.16.1 Spigot (Test Server)

**What Minecraft Client Version are you running?**
1.16.1 Vanilla
**What version of NOPE are you running?**
1.7.1 I think
**What is the debug ID?**
Autoclicker#1

**Is there any debug information? (Please include average info if available)**
Can't see I don't have perms :(
**What is causing this false positive?**
Holding down right-click when bridging
**Is this false positive reproducible on the test server?**
Found on the test server
**Is there anything else to add?**
Could you add an autoclicker check for both right and left click if possible.

**Comment by MSWS** [comment]
I was unable to replicate this by holding right click, sneaking, and bridging over air.
