### ISSUE TITLE
Players got kicked and their inventories are gone

### ISSUE THREAD

**Issue by alqassam1998** [MSWS/NOPE#158]
**What server version are you running?**
Paper 1.15.2 Build 350 

**What version of NOPE are you running?**
1.7.2

**What is the bug?**
Players get kicked, and their inventory were gone. It happens when the anti-cheat active, but it's not occurred frequently. So probably it caused by this plugin, or there are some conflicts with the other plugins. The plugin sends the report when a player gets kicked. I will send some false positive warnings on another issue.

**Please list your plugins below**
Additions, AdvancedNMotd*, AntiBotDeluxe*, BetterSleeping3, BKCommonLib, BlockLocker, Citizens, ColoredSigns*, CommandButtons, CoreProtect, CraftBook, CrazyAuctions, DriveBackupV2*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, GroupManager, HolographicDisplays, Jobs, LoginSecurity*, Minepacks, NOPE, NoPlugins, PlaceholderAPI, ProtocolLib, Quests, QuickShop, SkinsRestorer, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, Wild, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Is there anything else to add?**
The plugin runs just fine.

**Comment by MSWS** [comment]
NOPE does not interfere with inventories aside from a few packets (these don't affect server-side inventories either). Unless there is more detail then I cannot do much about this.
