### ISSUE TITLE
Some checks triggered when the player has bad connection

### ISSUE THREAD

**Issue by alqassam1998** [MSWS/NOPE#159]
**What server version are you running?**
Paper 1.15.2 Build 350

**What Minecraft Client Version are you running?**
1.16.1

**What version of NOPE are you running?**
1.7.2

**What is the debug ID?**
Speed#1
Speed#4
Timer#1
KillAura#1
KillAura#4

**Is there any debug information? (Please include average info if available)**
No, just some hack numbers

**What is causing this false positive?**
It happens when the players have high ping.
Speed hacks are triggered even when players stand or walk normally

**Is this false positive reproducible on the test server?**
Not tested

**Please list all your server plugins**
Additions, AdvancedNMotd*, AntiBotDeluxe*, BetterSleeping3, BKCommonLib, BlockLocker, Citizens, ColoredSigns*, CommandButtons, CoreProtect, CraftBook, CrazyAuctions, DriveBackupV2*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, GroupManager, HolographicDisplays, Jobs, LoginSecurity*, Minepacks, NOPE, NoPlugins, PlaceholderAPI, ProtocolLib, Quests, QuickShop, SkinsRestorer, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, Wild, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Is there anything else to add?**
That's all.

**Comment by tkn0** [comment]
Fix your config, if you need some help with configuration, reach out to me on discord I can provide some decent settings. tekn0#8418 in MSWS discord.

**Comment by MSWS** [comment]
I've gone ahead and remove Speed#4 as it consistently triggerd falsely on a poor connection. However, I haven't been able to find a consistent false positive with the other checks. Additionally, any false positives I did find relied on the player having a ping of > 250.
