### ISSUE TITLE
Fake Positives again

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#16]
**What server version are you running?**
Spigot: 1.15.2

**What version of NOPE are you running?**
1.2.4

**What is the bug?**
Still many false positives, If the player hits an entity he is sighed of kill aura or critical.

If his game freeze, he is sighed of Timer 
And I still have a lot of Step alerts as the player just jumps or steals.

**Is there anything else to add?**
Screen;

![2020-05-06_15 26 57](https://user-images.githubusercontent.com/39565971/81182664-646a7000-8fae-11ea-98d7-9ef36a7082bd.png)

**Comment by MSWS** [comment]
Please use the False Flag format and enable DEV Mode.

**Comment by Neiy0** [comment]
Sorry, I’ll do it next time
![2020-05-06_15 37 22](https://user-images.githubusercontent.com/39565971/81183504-8adcdb00-8faf-11ea-9697-6accac1d3ff8.png)

**Comment by MSWS** [comment]
Please create a new issue using the proper template.
