### ISSUE TITLE
hitting an animal gets you kicked and gives error

### ISSUE THREAD

**Issue by Omegabiebel** [MSWS/NOPE#160]
**What server version are you running?**
bungeecord latest with paper 1.16.1 nr39

**What version of NOPE are you running?**
1.7.2

**What is the bug?**
you hit a mob and it kicks you. You can see it yourself in the video I provided.

**Please list your plugins below**
I tested it with protocollib and NOPE alone, and the bug still occurred.
**Is there anything else to add?**
yes.
video:https://we.tl/t-mKHYNRNnlJ
error log:

[12:28:32 INFO]: [NOPE] You are using an up-to-date version.
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.comphenix.net.sf.cglib.core.ReflectUtils$1 (file:/Users/superbiebel/Desktop/servers/gaudium%20network/lobby/plugins/ProtocolLib.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.comphenix.net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[12:29:59 INFO]: UUID of player Superbiebel is b7ed3c3a-4e94-4887-8f54-07a1f77b2819
[12:30:00 INFO]: Superbiebel joined the game
[12:30:00 INFO]: Superbiebel[/127.0.0.1:50571] logged in with entity id 264 at ([world]-308.3657870290628, 65.46206874297104, 277.6804154726116)
[12:30:03 INFO]: Superbiebel lost connection: Disconnected
[12:30:03 INFO]: Superbiebel left the game

NOTE: i am on a mac.

**Comment by MSWS** [comment]
Does this happen without ProtocolLib?

**Comment by Omegabiebel** [comment]
havent tested it, I will test it now

**Comment by Omegabiebel** [comment]
tested it, I think it is protocollib because the bug doesn't occur. 

btw, damn, you responded within 30 seconds!

**Comment by MSWS** [comment]
Unfortunately it's probably a ProtocolLib issue, you can try using the 1.16 beta issue however I would recommend removing ProtocolLib for now and wait for the 1.16 version to officially update.

**Comment by Omegabiebel** [comment]
The bug isn't entirely caused by protocolib I think because when I remove NOPE the bug is also gone

**Comment by MSWS** [comment]
NOPE might be using some ProtocolLib methods that simply haven’t been updated for 1.16, if/when it updates I’ll be able to fix it if it’s still an issue.

**Comment by Omegabiebel** [comment]
okay, thx for your super fast response
