### ISSUE TITLE
Flight#2, Flight#3, Flight#4, and Step#1 Set off when the player has levitation

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#161]
**What server version are you running?**
1.16.1 Paper Spigot
**What Minecraft Client Version are you running?**
1.15.1 Vanilla
**What version of NOPE are you running?**
1.6.3
**What is the debug ID?**
Flight#2, Flight#3, Flight#4, Step#1
**Is there any debug information? (Please include average info if available)**
I have a video recording I can provide for this, but I think it is easy to recreate.
**What is causing this false positive?**
Getting hit by a shulker and getting the levitation effect.
**Is this false positive reproducible on the test server?**
Yes

**Comment by MSWS** [comment]
This should be patched in 1.7.3, for future bug reports I recommend using the latest version of NOPE.
