### ISSUE TITLE
Bug - We get expelled when we break a block of basalt or black rock.

### ISSUE THREAD

**Issue by LePatriote** [MSWS/NOPE#163]
**What server version are you running?**
1.16.1 Paper Spigot

**What version of NOPE are you running?**
1.7.2

**What is the bug?**
(Sorry I don't speak English)
Quand on casse un bloc de 'blackstone' ou de 'basalt' (je n'ai pas essayé avec d'autres blocs), l'anti-cheat replace de force la vue du joueur vers le bloc. Et si on essaye de casser plusieurs blocs de 'blackstone' ou de 'basalt' à la suite, l'animation de ban s'active et le joueur est kick.

**Please list your plugins below**
NOPE AntiCheat

**Is there anything else to add?**
//

**Comment by tkn0** [comment]
You are probably flagging fastbreak as the block breaks quickly and most likely wasn't added to the ac's checks in the update. Feel free to contact me on discord @tekn0#8418 in the MSWS discord and I can help you with your config.

**Comment by MSWS** [comment]
tkn0 is correct, I missed adding new 1.16 blocks in the 1.7 update. Thank you for reporting, these should be patched in 1.7.3.
