### ISSUE TITLE
Nether Vines false flight

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#164]
**What server version are you running?**
Paper Spigot 1.16.1
**What Minecraft Client Version are you running?**
1.16.1 Vanilla
**What version of NOPE are you running?**
1.7
**What is the debug ID?**
Unknown
**Is there any debug information? (Please include average info if available)**
Unknown
**What is causing this false positive?**
Climbing on nether vines
**Is this false positive reproducible on the test server?**
Unknown as I can't play due to Lib bugs

**Comment by MSWS** [comment]
This should be patched in 1.7.3. Thanks for reporting!
