### ISSUE TITLE
Dying and falling to your death over and over again flags step. (V1.7)

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#165]
**What server version are you running?**
Paper 1.16.1
**What Minecraft Client Version are you running?**
Vanilla 1.16.1
**What version of NOPE are you running?**
1.7
**What is the debug ID?**
Step#1
**Is there any debug information? (Please include average info if available)**
Avg. 1.37052...
Size 6

**What is causing this false positive?**
Dying by spawning at a bed and falling to your death over and over again
**Is this false positive reproducible on the test server?**
Probably

**Comment by MSWS** [comment]
I was unable to replicate this. Please provide more details.
