### ISSUE TITLE
Fake Positives 

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#17]
**What server version are you running?**
Spigot: 1.15.2

**What Minecraft Client Version are you running?**
1.15.2 Optifine

**What version of NOPE are you running?**
1.2.4

**What is the debug ID?**
![2020-05-07_08 35 34](https://user-images.githubusercontent.com/39565971/81262279-d50c9d80-903d-11ea-9336-0f49212fc13e.png)
![2020-05-07_08 35 38](https://user-images.githubusercontent.com/39565971/81262280-d5a53400-903d-11ea-840f-3d231ee259c6.png)

**Is there any debug information?**

When I jump:

![2020-05-07_08 36 59](https://user-images.githubusercontent.com/39565971/81262330-ef467b80-903d-11ea-9c86-b3119ce09315.png)

For the timer it's when i lag FPS i move fast

**What is causing this false flag?**
For Step: I just Jump.
For Timer: It's when I lag FPS and I move fast. (Mini teleport)

**Is there anything else to add?**
Nothing

**Comment by MSWS** [comment]
The timer flags are very minor and should not interfere with gameplay that much. If there is consistent false flags regarding it do tell me. I have updated NOPE and the step bug should be fixed.

**Comment by Neiy0** [comment]
I test and i say you :)

**Comment by Neiy0** [comment]
![2020-05-07_09 32 51](https://user-images.githubusercontent.com/39565971/81266845-c3c78f00-9045-11ea-88e6-4149311a238a.png)
Nop always :/ And Spider & SafeWalk xD

**Comment by MSWS** [comment]
This is NOPE 1.2.5 right? Does this happen on the ground (not in the trees) or in a superflat world?

**Comment by Neiy0** [comment]
Yes it's the 1.2.5, and I jump from everywhere or jump on the spot

**Comment by Neiy0** [comment]
Ho my bad, it's 1.2.4 wtf, but But I just downloaded it, i restart my server and say it :x :x

**Comment by Neiy0** [comment]
I have always

**Comment by Neiy0** [comment]
it's just when I execute /nope the version is 1.2.4 x) it's not me

**Comment by MSWS** [comment]
Sorry can you clarify if it's still occuring?

**Comment by Neiy0** [comment]
Yes, I have step allert

**Comment by MSWS** [comment]
If you can, please join my discord so we can talk about this more easily.

https://discord.gg/xCFvu8J

**Comment by Neiy0** [comment]
Yes i can't speak because my english is very bad, but i can screenshare
