### ISSUE TITLE
Players Being Flagged For FastBreak

### ISSUE THREAD

**Issue by iFrgot** [MSWS/NOPE#170]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.15.2 Spigot
**What Minecraft Client Version are you running?**
Minecraft Vanilla
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
Nope 1.7.2
**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_
FastBreak#1
**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_
Type: Vine 
Time Diff: -847
Hardness: 0.2
**What is causing this false positive?**
_What exactly are you doing that causes a false positive?_
They are usually just mining and they just are flagged, I think it is because they are lagging, but when I check their ping they have under 80 which is normal ping.
**Is this false positive reproducible on the test server?**
_MSWS.xyz is the IP_
I can not connect as the server is on 1.16.1 and I am on 1.15.2
**Please list all your server plugins**
WorldEdit, OpenInv, XRayDetector, PlaceholderAPI, ClearLag, AutoMessage, BuycraftX, Votifier, ProtocolLib, Multiverse-Core, WorldGuard, PermissionsEx, Vault, HideStream, GriefProtection, PluginHiderPlus, StackMob, LastLoginAPI, Essentials, QuickBoard, Parties, NOPE, VillagerShopGUI, RankGrantPlus, HologramDisplays, DeadChest, AuctionHouse, VotingPlugin, SuperVanish, BetterRTP, EssentialsSpawn, ChatManager, CrazyCrates.
**Is there anything else to add?**
I think the anti-esp might be affecting them as there are a lot of entities being created and their connections might not be able to handle it, just a thought though.

**Comment by MSWS** [comment]
Thanks for reporting this, the false positive occurred when breaking vines. This should be patched in 1.7.3.
