### ISSUE TITLE
Floating Entities

### ISSUE THREAD

**Issue by iFrgot** [MSWS/NOPE#171]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.15.2 Spigot
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.7.2
**What is the bug?**
_Please be descriptive_
You can sometimes see a copy of your player floating behind you, if you spin fast enough or f5 you can see it, I have also seen a diamond helmet popping up inside your inventory.
**Please list your plugins below**
WorldEdit, OpenInv, XRayDetector, PlaceholderAPI, ClearLag, AutoMessage, BuycraftX, Votifier, ProtocolLib, Multiverse-Core, WorldGuard, PermissionsEx, Vault, HideStream, GriefProtection, PluginHiderPlus, StackMob, LastLoginAPI, Essentials, QuickBoard, Parties, NOPE, VillagerShopGUI, RankGrantPlus, HologramDisplays, DeadChest, AuctionHouse, VotingPlugin, SuperVanish, BetterRTP, EssentialsSpawn, ChatManager, CrazyCrates.
**Is there anything else to add?**
_Are there any error logs?_

**Comment by MSWS** [comment]
This is intended.

**Comment by iFrgot** [comment]
What is intended about it, the floating entity? I don't think the player should be able to see it

**Comment by MSWS** [comment]
It is intended to catch blatant kill aura.

**Comment by iFrgot** [comment]
The floating character?

**Comment by MSWS** [comment]
Yes

**Comment by iFrgot** [comment]
I just thought of this, is it because I have permissions that I can see this character? Or can anyone see it?

**Comment by MSWS** [comment]
Anyone can see this.

**Comment by iFrgot** [comment]
Is it possible so that the player wont see it?

**Comment by MSWS** [comment]
Not without disabling the check (KillAura#3), you can do this in the config.

**Comment by iFrgot** [comment]
so if I disabled killaura#3 only, the check will still be there but the floating character won't?

**Comment by MSWS** [comment]
N,o the check will be disabled as I said and the character will no longer be there.

**Comment by iFrgot** [comment]
What do killaura checks 1,2,4 and 5 do then?

**Comment by MSWS** [comment]
I would recommend checking the source code to see what they do.
