### ISSUE TITLE
Anti Dupe

### ISSUE THREAD

**Issue by iFrgot** [MSWS/NOPE#172]
**Is your feature request related to a problem/bug?**
No
**Describe the solution you'd like**
It would be nice to have an anti dupe feature with the anitcheat
**Have you tried implementing this solution alternatively?**
_Either through the config or separate plugins_
I don't know how to do such a thing in the config, the seperate plugins don't patch a specific dupe.
**Additional context**
Add any other context or screenshots about the recommendation please put here. This includes if the feature request involves a separate plugin, please make sure to link the plugin.
The main dupe I would want patched is the mule dupe in multiplayer, where a player is on a mule with the items in the mule's chest, they disconnect while another player is looking inside the chest, the player on the mule disconnects and the player looking in the chest takes the items out, the player on the mule logs back on and takes the items out of the mule and there are double.

**Comment by MSWS** [comment]
Players can dupe without a hack client so it’s not a hack. This is outside the scope of NOPE.

**Comment by tkn0** [comment]
Go download illegal stack

**Comment by iFrgot** [comment]
I know its not a hack, I just said it would be a cool feature, and tkn0 illegal stack doesn't mention it patching this dupe

**Comment by tkn0** [comment]
Illegal Stack literally patches this constantly. Every server uses illegal stack unless they have someone to dev a similar plugin.

**Comment by iFrgot** [comment]
ok thanks
