### ISSUE TITLE
I don't know iis this a bug or a false check

### ISSUE THREAD

**Issue by LucidVerse** [MSWS/NOPE#173]
**Minecraft 1.16.1 spigot**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_

**When a player join whitout op, it kicks out : Irregular gameplay for flight#1 it kick during : login , when teleporting with multiverse**
_Please be descriptive_

**Plugins (29): LuckPerms, PluginConstructorAPI, LoginSecurity, PlaceholderAPI, ClearLag, spark, ProtocolLib, AdvancedPortals, VoidGenerator, NoteBlockAPI, PerWorldPluginsPremium, Vault, Statz, WorldEdit, AnimatedScoreboard, AntiCheatReloaded, ClearLagTimer, PerWorldInventory, WorldGuard, Multiverse-Core, ChatEx, Multiverse-NetherPortals, GriefPrevention, DeluxeHub, Essentials, BedWars, RandomTP, EssentialsChat, IridiumSkyblock**

**[21:29:19] [Server thread/INFO]: [NOPE] SkyAdmin failed Flight#1
[21:29:24] [Server thread/INFO]: [NOPE] SkyAdmin failed Flight#1
[21:29:25] [Server thread/INFO]: SkyAdmin lost connection: Irregular Gameplay
[21:29:25] [Server thread/INFO]: [-] SkyAdmin Lelépett a szerverről!
**
_Are there any error logs?_

**Comment by MSWS** [comment]
This is a false positive, please re-report it using the proper format.

**Comment by steviebeenz** [comment]
I'm not MSWS but the anticheat detected you for fly.

**Comment by LucidVerse** [comment]
Yes /fly can make you fly
