### ISSUE TITLE
Fly problem

### ISSUE THREAD

**Issue by LucidVerse** [MSWS/NOPE#174]
**1.16.1 spigot **
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_

**What Minecraft Client Version are you running?**

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_

**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_

**Is there any debug information?

**If you ise Deluxehub AND make it to maanage to /fly command it buggs out and kick you for fly irragular game**

**Is this false positive reproducible on the test server?**
_MSWS.xyz is the IP_

** dPlugins (29): �LuckPerms�, �PluginConstructorAPI�, �LoginSecurity�, �PlaceholderAPI�, �ClearLag�, �spark�, �ProtocolLib�, �AdvancedPortals�, �VoidGenerator�, �NoteBlockAPI�, �PerWorldPluginsPremium�, �Vault�, �Statz�, �WorldEdit�, �AnimatedScoreboard�, �AntiCheatReloaded�, �ClearLagTimer�, �PerWorldInventory�, �WorldGuard�, �Multiverse-Core�, �ChatEx�, �Multiverse-NetherPortals�, �GriefPrevention�, �DeluxeHub�, �Essentials�, �BedWars�, �RandomTP�, �EssentialsChat�, �IridiumSkyblock�**
**I just think this is caused by Deluxehub fly but its a flight problem**

**Comment by steviebeenz** [comment]
Having same problem, I just moved off Deluxehub as it has other problems and severe incompatibilities. I moved to Super Lobby Deluxe + HubThat.

**Comment by steviebeenz** [comment]
@BossMcSzerver It's due to the way Deluxehub works, moving to a different hub plugin or using essentials to override the fly, and gamemode commands seems to fix it.

It has compatibility issues with other anticheats and plugins as well.

**Comment by LucidVerse** [comment]
Ok I report this to Deluxehub support

**Comment by steviebeenz** [comment]
Thanks, on behalf of all the anticheat Devs in the world.

Tell them to reset your flight and gamemode and change it again every time
you switch world.

**Comment by MSWS** [comment]
I was unable to confirm this using DeluxeHub 3.3.7, please re-open and provide further detail/explanation if this issue is still occuring.
