### ISSUE TITLE
Flying witch when ringing the bells

### ISSUE THREAD

**Issue by alqassam1998** [MSWS/NOPE#175]
**What server version are you running?**
Paper 1.15.2 latest build

**What version of NOPE are you running?**
1.7.2

**What is the bug?**
Witch flying around like anti-KillAura does when ringing the bells. Also, anti-KillAura still appears even it is disabled in the config.

**Please list your plugins below**
Additions, AdvancedNMotd*, AntiBotDeluxe*, BetterSleeping3, BKCommonLib, BlockLocker, Citizens, ColoredSigns*, CommandButtons, CoreProtect, CraftBook, CrazyAuctions, DriveBackupV2*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, GroupManager, HolographicDisplays, Jobs, LoginSecurity*, Minepacks, MobFarmManager, NOPE, NoPlugins, PlaceholderAPI, ProtocolLib, Quests, QuickShop, SkinsRestorer, Train_Carts, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, Wild, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Is there anything else to add?**
No error logs

**Comment by MSWS** [comment]
I was unable to confirm, please provide screenshots of what exactly is happening and re-open.
