### ISSUE TITLE
I hit an NPC that was created with the Citizens plugin and I got this error in the console

### ISSUE THREAD

**Issue by Seff300** [MSWS/NOPE#176]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper 1.16.1
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.7.3

**What is the bug?**
_Please be descriptive_
I hit an NPC that was created with the Citizens plugin and I got this error in the console
https://pastebin.com/vN7uB91S

**Please list your plugins below**
AdvancedBan, BedWars, BungeeTabListPlus, Citizens, CommandPanels, FastAsyncWorldEdit, HolographicDisplays,, LuckPerms, Multiverse-Core, NOPE, PlaceholderAPI, ProtocolLib, PunishmentGUI, SBAHypixelify, SuperVanish, My custom report plugin, Vault, My custom chat plugin, A custom voting plugin made for my server by a Developer, NuVotifier, WooMinecraft, WorldGuard and XPWars

**Is there anything else to add?**
_Are there any error logs?_
https://pastebin.com/vN7uB91S

**Comment by MSWS** [comment]
This is a Protocol issue.
