### ISSUE TITLE
Player using crossbow gets flagged for fastbow

### ISSUE THREAD

**Issue by MeyerOppelt** [MSWS/NOPE#177]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.16.1 Paper
**What Minecraft Client Version are you running?**
1.16.1 Vanilla
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
NOPE 1.7.3
**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_
FastBow#1
**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_
I dont see this in game
**What is causing this false positive?**
_What exactly are you doing that causes a false positive?_
Using A crossbow instead of a bow
**Is this false positive reproducible on the test server?**
_MSWS.xyz is the IP_
I cant connect to the server
**Please list all your server plugins**
ChestLockGui*, ChestShop, ConsoleSpamFix, CoreProtect, DiscordSRV, dynmap*, Dynmap-GriefPrevention*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FastAsyncWorldEdit, GriefPrevention, InventoryRollback, Jobs, LuckPerms, NametagEdit*, NOPE, OpenInv, PlayerKits, PlayerWarps, RankGrantPlus, SkQuery, Skript, StaffChatReloaded, Vault, WebConsole, WorldEdit, WorldGuard
**Is there anything else to add?**
No, I dont think so

**Comment by MSWS** [comment]
I was unable to confirm this is an issue even with loading 9 crossbows all at once and shooting them in quick succession.
