### ISSUE TITLE
False positive ladder

### ISSUE THREAD

**Issue by SKBotNL** [MSWS/NOPE#178]
**What server version are you running?**
Minecraft 1.16.1
Paper 1.16.1

**What Minecraft Client Version are you running?**
Wurst 1.16.1

**What version of NOPE are you running?**
1.7.3

**What is the debug ID?**
AutoClicker#1

**Is there any debug information? (Please include average info if available)**
I think not

**What is causing this false positive?**
If you climb a ladder, hold right click and place new ladders

**Is this false positive reproducible on the test server?**
Didn't test

**Please list all your server plugins**
NOPE
ProtocolLib

**Is there anything else to add?**
No

**Comment by MSWS** [comment]
Placing and climbing on a stack of stone with ladders all the way to 255 yielded no false flags relating to autoclicker.
