### ISSUE TITLE
The Toggle command doesn't work

### ISSUE THREAD

**Issue by Seff300** [MSWS/NOPE#181]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper 1.16.1
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.7.3

**What is the bug?**
_Please be descriptive_
I tried to use the /toggle command but the command doesn't even seem to exist

**Please list your plugins below**
AdvancedBan, BedWars, BungeeTabListPlus, BPI, Citizens, CommandPanels, HolographicDisplays,, LuckPerms, Multiverse-Core, NOPE, PlaceholderAPI, ProtocolLib, PunishmentGUI, SBAHypixelify, SuperVanish, My custom report plugin, Vault, My custom chat plugin, A custom voting plugin made for my server by a Developer, NuVotifier, WooMinecraft, WorldGuard and WorldEdit

**Is there anything else to add?**
_Are there any error logs?_
No

**Comment by MSWS** [comment]
It's /nope toggle and /nope report

**Comment by Seff300** [comment]
On the wiki it said it was just /report And the toggle I just found out

**Comment by MSWS** [comment]
I'll fix the wiki.
