### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Kruize1** [MSWS/NOPE#183]
**What server version are you running?**
Paper 1.16.1 , (115)

**What version of NOPE are you running?**
1.7.3

**What is the bug?**
https://pastebin.com/wsCStPvp

**Please list your plugins below**

**Is there anything else to add?**
https://pastebin.com/wsCStPvp

**Comment by MSWS** [comment]
This is a ProtocolLib issue. You can either disable protocollib or try using a beta version.
