### ISSUE TITLE
Kill aura and Step 

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#19]
**What server version are you running?**
Spigot 1.15.2

**What Minecraft Client Version are you running?**
1.15.2 Optifine

**What version of NOPE are you running?**
1.2.8

**What is the debug ID?**
![2020-05-12_17 55 54](https://user-images.githubusercontent.com/39565971/81716591-d7298e80-9479-11ea-8fb1-dcacde129ec9.png)

**Is there any debug information? (Please include average info if available)**
![2020-05-12_17 55 06](https://user-images.githubusercontent.com/39565971/81716521-c2e59180-9479-11ea-9712-78c2c064b1ee.png)
![2020-05-12_17 55 09](https://user-images.githubusercontent.com/39565971/81716523-c416be80-9479-11ea-87c4-9010ac5b63ba.png)

**What is causing this false flag?**
For the FF It's when I hit a entity and the server lag OR the player game freeze, because when I hit the entity if my game freeze, I don't move but the mob yes, and is it's the server, i can hit the entity and move. I THINK. And for the step, I’m just walking around jumping into a normal map

**Is there anything else to add?**
Nop, good plugin

**Comment by Neiy0** [comment]
And if you can't remove this if a player jump x)

![2020-05-12_17 58 45](https://user-images.githubusercontent.com/39565971/81716922-3e474300-947a-11ea-89fd-f629ff779be8.png)

**Comment by Neiy0** [comment]
![2020-05-12_17 59 52](https://user-images.githubusercontent.com/39565971/81717058-633bb600-947a-11ea-8a73-12e73a216a4d.png)
![2020-05-12_17 59 50](https://user-images.githubusercontent.com/39565971/81717064-63d44c80-947a-11ea-9ea6-a0a16c5f7591.png)
![2020-05-12_17 59 44](https://user-images.githubusercontent.com/39565971/81717068-65057980-947a-11ea-9cb2-489496008d4d.png)

**Comment by Neiy0** [comment]
![2020-05-12_18 00 48](https://user-images.githubusercontent.com/39565971/81717252-9aaa6280-947a-11ea-829e-b57c773f79a6.png)
![2020-05-12_18 00 49](https://user-images.githubusercontent.com/39565971/81717268-9da55300-947a-11ea-9805-f5fc79907d36.png)
![2020-05-12_18 00 50](https://user-images.githubusercontent.com/39565971/81717278-a007ad00-947a-11ea-9d4b-63b843128f97.png)
![2020-05-12_18 00 50_2](https://user-images.githubusercontent.com/39565971/81717285-a1d17080-947a-11ea-85eb-6c66d749e3b4.png)
![2020-05-12_18 00 47](https://user-images.githubusercontent.com/39565971/81717293-a433ca80-947a-11ea-970a-c9b2b82cef00.png)

**Comment by MSWS** [comment]
Step has been resolved, I will look more into Kill Aura.
