### ISSUE TITLE
Towering

### ISSUE THREAD

**Issue by SKBotNL** [MSWS/NOPE#199]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.16.2 Paper

**What Minecraft Client Version are you running?**
1.16.2 Inertia

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.8.1

**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_
Autoclicker

**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_
Idk

**What is causing this false positive?**
_What exactly are you doing that causes a false positive?_
Towering

**Is this false positive reproducible on the test server?**
_MSWS.xyz is the IP_
I can't get on the server

**Please list all your server plugins**
- NOPE

**Is there anything else to add?**
No

**Comment by MSWS** [comment]
Unable to confirm, please provide more detail / steps to recreate.
