### ISSUE TITLE
Fall Distance messages still show up even if DevMode is turned off

### ISSUE THREAD

**Issue by cs127** [MSWS/NOPE#20]
**What server version are you running?**
Paper 1.15.2

**What version of NOPE are you running?**
1.2.8

**What is the bug?**
Exactly what the title says.

**Is there anything else to add?**
_Are there any error logs?_
No

**Comment by MSWS** [comment]
I will look into this, thank you.

**Comment by MSWS** [comment]
This will be patched in 1.2.9.
