### ISSUE TITLE
Bug Report - Server crashes when options are disabled.

### ISSUE THREAD

**Issue by Jaymate123** [MSWS/NOPE#200]
**What server version are you running?** 
1.16.2
**What version of NOPE are you running?**
1.8.1
**What is the bug? Please be descriptive**
![image](https://user-images.githubusercontent.com/44719990/91848226-fe60d180-ec9d-11ea-9cb1-15c2cc9d39ad.png)
this happens when I punch something after disabling some checks due to false positives
Please list your plugins below
![image](https://user-images.githubusercontent.com/44719990/91848778-4c75d500-ec9e-11ea-89b5-360f211de209.png)

**Is there anything else to add? Are there any error logs?**
Here is my settings, unless I accidentally did something else, all I did was disable CPS check and Fastbreak check due to false postives.

`
#             ----------------------------------------------------------             
#                                                                                    
#                            NOPE Anti-Cheat Configuration                           
#                                                                                    
#               This is the configuration for NOPE. I recommend keeping              
#                the default values unless you know what you're doing.               
#                                                                                    
#                      There is a YouTube tutorial available at                      
#                     https://www.youtube.com/watch?v=XVuXKsJEAkQ                    
#                                                                                    
#                        There is a GitHub wiki tutorial also                        
#                       available at https://NOPE.MSWS.xyz/wiki                      
#                                                                                    
#             ----------------------------------------------------------             

ConfigVersion: 1.8.1

#                           -------------------------------                          
#                                Global Configuration                                
#                           -------------------------------                          

Global: true # If disabled, NOPE will be disabled
Scoreboard: true # The scoreboard uses the vanilla scoreboard and shouldn't mess with other plugins

Log: file # NONE, file, or hastebin
GitHub: # Fill out these fields to enable /nope false, leave Password blank to use a TAP (recommended), see https://github.com/settings/tokens for more details
  Username: ''
  Password: ''

# Permission to be notified ingame is nope.message.udpate
UpdateChecker:
  Enabled: true
  InGame: true
BungeeNameOverride: '' # If not empty this will override the server name
# This is useful for replacing %server% if the server is not bungeecord

# VL Decrement is responsible for decrementing VL levels for players that haven't flagged for a while
# The key is the time in milliseconds since the player last flagged for a hack. For example
# if a player hasn't flagged for 20000 milliseconds, their VL will be decreased by 2 every second
VLDecrement:
  Enabled: true
  Rate: 40 # Ticks
  Periods:
    1000: 0
    10000: 1
    20000: 2
    60000: 5
    120000: 10
    -1: 20
#                           -------------------------------                          
#                                Banwave Configuration                               
#                           -------------------------------                          

BanwaveRate: 36000 # Rate of banwave (in ticks) -1 to disable

# If enabled, developer messages will be sent to the player and commands will not execute
DevMode: false
DebugMode: false

#                           -------------------------------                          
#                                Webhook Configuration                               
#             Webhooks allow a server to send POST requests to a webhook.            
#                   If you do not know about this then I recommend                   
#                 Googling or asking someone for help regarding this.                
#                 For Discord specific configuration you can look at                 
#        https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html       
#and https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks?page=1
#      for help. All arguments are supported that are defined in the first link.     
#                 Placeholders listed below in Actions are supported                 
#                           -------------------------------                          

Webhooks:
  banExample:
    URL: 'https://discordapp.com/api/webhooks/'
    username: 'NOPE'
    avatar_url: 'https://i.imgur.com/JLKC7CN.jpg'
    embeds:
      author:
        name: "%player% Ban"
        avatar_url: 'https://i.imgur.com/JLKC7CN.jpg'
      title: '%player% was banned for %check%'
      color: 14483456
      fields:
        check:
          name: "Check"
          value: "%debug%"
        world:
          name: "World"
          value: "%world%"
        vl:
          name: "VL"
          value: "%vl%"
          inline: false
  flagExample:
    URL: 'https://discordapp.com/api/webhooks/'
    username: 'NOPE'
    avatar_url: 'https://i.imgur.com/JLKC7CN.jpg'
    embeds:
      author:
        name: "%player%"
        icon_url: 'https://crafatar.com/avatars/%uuid%'
      title: '%player% flagged %check%'
      color: 751818
      fields:
        1:
          name: "Player"
          value: "%player%"
        2:
          name: "World"
          value: "%world%"
        3:
          name: "Server"
          value: "%server%"
          inline: true
        4:
          name: "VL"
          value: "%vl%"
        5:
          name: "Check"
          value: "%debug%"
        6:
          name: "UUID"
          value: "%uuid%"
     #thumbnail:
     #  url: ''
     #image:
     #  url: ''
      footer:
        text: "MSWS.XYZ"
       #icon_url: ''

#                           -------------------------------                          
#                                Action Configuration                                
#              Please note that bans are not necesssarily instantaneous.             
#                    Please add a delay to prevent duplicate bans.                   
#
#
# animation:[TYPE]:Action         | TYPEs are NOPE or GWEN, the Action should be a custom command                  
# kick:Reason                     | Kick the player for the specified reason                                       
# ban:Time:Reason                 | Ban the player for the specified time/reason                                   
# banwave:Time:Reason             | Add the player to the banwave                                                  
# cancel                          | Teleport the player back                                                       
# pmsg:[Message]                  | Send a message to the player                                                   
# msg:[all/Permission]:[Message]  | Can also specify all                                                           
# cmd:[Command]                   | Run a command as the player                                                    
# ccmd:[Command]                  | Run a command from console                                                     
# log:type:message                | Logs the message either to FILE, INGAME, or CONSOLE (perm: nope.message.normal)
# log:WEBHOOK:message             | Logs the message to the specified webhook                                      
# setvl:VL                        | Sets the player's VL for the category hack                                     
# addvl:VL                        | Adds/Modifies the player's VL for the category hack                            
#
# Conditions: (<, <=, =, !=, >=, >)
# If a condition is not fullfilled, none of the following actions will be run
# The ones with > you can replace with the appropriate operator
#
# vl>[Amo]       | If the VL matches the threshold                                                                                       
# tps>[Amo]      | If the server's TPS matches the threshold                                                                             
# ping>[Amo]     | If the player's ping matches (NOT RECOMMENDED) players can spoof their ping                                           
# delay:[Delay]  | Wait X milliseconds before executing the NEXT action (eg: kick a player if the last call of this was > 60 seconds ago)
# notdev         | Will not run the next actions if the in dev mode                                                                      
# isdev          | Will run the next actions if in dev mode                                                                              
# rnd:.40        | Will run the actions 40% of the time                                                                                  
# 
#                                    Placeholders                                    
# %player%  | The name of the player that was banned                                                   
# %uuid%    | The UUID of the player (-'s included)                                                    
# %nuuid%   | The UUID of the player (-'s not included)                                                
# %check%   | What hack the player was banned for                                                      
# %debug%   | The debug ID of the check                                                                
# %vl%      | The VL of the hack that the player was at when they were banned                          
# %world%   | What world the player was in when they were banned, this may be null if they were offline
# %token%   | The ban token (only for ban)                                                             
# %server%  | The server name, useful for webhooks                                                     
#
# PAPI is also supported
#                           -------------------------------                          

Actions:
  FastBreak:
  - 'basiclog|cancel|vl>100|tpsdecrement|tpskick|vl>400|lagkick|tps>15|vl>600|cban'
  FastClimb:
  - 'basiclog|vl>50|delay:1000|cancel|vl>200|cancel|vl>400|ikick|vl>600|cban'
  Blink:
  - 'basiclog|delay:30000|cancel|vl>200|delay:2000|cancel|delay:15000|tpsdecrement|tps>15|vl>300|lagkick|vl>500|cancel|vl>800|cban'
  NoSwing:
  - 'basiclog|vl>500|ikick|vl>1000|cban'
  Speed:
  - 'basiclog|rndcancel|vl>100|cancel|vl>300|lagkick|vl>400|ikick|vl>800|addbanwave|vl>1200|cban'
  ElytraFlight:
  - 'basiclog|vl>500|ikick|vl>800|addbanwave|vl>1000|cban'
  Timer:
  - 'basiclog|vl>300|rndcancel|delay:10000|tpsdecrement|vl>500|lagkick|vl>600|ikick|vl>800|cban'
  KillAura:
  - 'basiclog|vl>200|ikick|vl>500|delay:120000|kick:Irregular Gameplay|vl>600|cban'
  NoFall:
  - 'basiclog|vl>300|ikick|vl>800|cban'
  SafeWalk:
  - 'basiclog|vl>500|ikick'
  AntiKB:
  - 'basiclog|tps>15|delay:20000|lagkick|vl>500|ikick|vl>800|cban'
  Default:
  - 'basiclog|vl>20|cancel|vl>100|flog|vl>200|lagkick|tps>15|vl>400|ikick|vl>800|addbanwave|vl>1200|cban'
  # You can specify multiple actiongroups for one category
 #- 'vl>50|delay:10000|ccmd:say %player% is suspected of using %check%'
 # This would only kick players and decrement their VL by 200
 #- 'basiclog|vl>100|cancel|vl>600|ikick|addvl:-200'
 # You can also specify a specific debug name and that these actions will be run instead
 #Flight#3:
  #- 'basiclog|delay:60000|say %player% flagged a %debug% check!'

# Commands are loaded and created in order. Define a custom command first before using it in another custom command.
Commands:
 #log Logs to a file that the player failed a check, and logs in console every 5 seconds that they failed the check
  flog: 'log:FILE:%player% failed %debug% (%vl%)'
 #the below actions log ingame an appropriate warning message to staff
  alog: 'vl>100|vl<300|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &a%check%&7 check. (VL: &e%vl%&7)'
  elog: 'vl>300|vl<500|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &e%check%&7 check. (VL: &e%vl%&7)'
  clog: 'vl>500|vl<700|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &c%check%&7 check. (VL: &e%vl%&7)'
  4log: 'vl>700|delay:500|flog|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &4%check%&7 check. (VL: &e%vl%&7)'
 #weblog Logs the action to the specified webhook (in this case flagExample) 
  weblog: "notdev|vl>400|delay:120000|log:flagExample:"
 #basiclog combines all above log commands into 1 for simple usage
  basiclog: 'alog|elog|clog|flog|4log|weblog'
 #logban Logs ingame that the player was banned both ingame and to a file
  logban: 'log:INGAME:&4&l[&c&lNOPE&4&l] &c%player% &7was banned for &b%check%&7.|log:FILE:Banned %player% for %debug% %vl%|delay:5000|log:banExample:'
 #ikick Kicks the player once every minute (to avoid constant kicking) in case they are stuck/otherwise false flagging 
  ikick: 'notdev|delay:60000|kick:Irregular Gameplay'
 #lagkick Kicks the player if their ping is too high
  lagkick: 'ping>150|delay:20000|kick:You seem to be very laggy, please try restarting your connection.'
 #tpskick Kicks the player if the server's TPS is too low
  tpskick: 'tps<=16|delay:40000|kick:The server is extremely laggy, please try waiting a bit before relogging.'
  tpsdecrement: 'tps<=16|addvl:-50'
 #rndcancel Has an 80% chance of teleporting the player back
  rndcancel: 'rnd:.80|cancel'
  canimate: "logban|ban:2628000000:&4NOPE Anti-Cheat&r\n&7Token: &e%token%"
 #cban Only bans the player if dev mode is disabled, it also logs the ban
 # We log the ban first so we can get the VL data first
  cban: "notdev|delay:5000|animation:NOPE:canimate"
  addbanwave: "notdev|banwave:2628000000:&4NOPE Anti-Cheat&r\n&7Token: &e%token%"

#                           -------------------------------                           
#                                 Check Configuration                                 
#               Here you can configure which checks are/aren't enabled                
#                  You can also toggle these ingame with /nope stats                  
#           make sure to restart your server after modifying these settings           
#                           -------------------------------           

Checks:
  Packet:
    Enabled: true
    SkinBlinker:
      Enabled: true
      SkinBlinker#1:
        Enabled: true
    Spinbot:
      Enabled: true
      Spinbot#1:
        Enabled: true
    NoSwing:
      Enabled: true
      NoSwing#1:
        Enabled: true
    PlayerESP:
      Enabled: true
      PlayerESP#2:
        Enabled: true
      PlayerESP#1:
        Enabled: true
    AutoSneak:
      Enabled: true
      AutoSneak#1:
        Enabled: true
    InvalidMovement:
      Enabled: true
      InvalidMovement#1:
        Enabled: true
    Timer:
      Enabled: true
      Timer#1:
        Enabled: true
    Blink:
      Enabled: true
      Blink#1:
        Enabled: true
  Movement:
    Enabled: true
    Speed:
      Enabled: true
      Speed#3:
        Enabled: true
      Speed#4:
        Enabled: true
      Speed#1:
        Enabled: true
      Speed#5:
        Enabled: true
      Speed#2:
        Enabled: true
    InventoryMove:
      Enabled: true
      InventoryMove#1:
        Enabled: true
    FastSneak:
      Enabled: true
      FastSneak#1:
        Enabled: true
    AutoWalk:
      Enabled: true
      AutoWalk#1:
        Enabled: true
    Glide:
      Enabled: true
      Glide#1:
        Enabled: true
    Flight:
      Enabled: true
      Flight#6:
        Enabled: true
      Flight#1:
        Enabled: true
      Flight#4:
        Enabled: true
      Flight#2:
        Enabled: true
      Flight#5:
        Enabled: true
      Flight#3:
        Enabled: true
    BHop:
      Enabled: true
      BHop#1:
        Enabled: true
    ElytraFlight:
      Enabled: true
      ElytraFlight#1:
        Enabled: true
    AntiRotate:
      Enabled: true
      AntiRotate#1:
        Enabled: true
    Jesus:
      Enabled: true
      Jesus#1:
        Enabled: true
      Jesus#2:
        Enabled: true
    AntiAFK:
      Enabled: true
      AntiAFK#1:
        Enabled: true
    NoSlowDown:
      Enabled: true
      NoSlowDown#1:
        Enabled: true
      NoSlowDown#2:
        Enabled: true
      NoSlowDown#5:
        Enabled: true
      NoSlowDown#3:
        Enabled: true
      NoSlowDown#4:
        Enabled: true
    Step:
      Enabled: true
      Step#1:
        Enabled: true
    Spider:
      Enabled: true
      Spider#1:
        Enabled: true
    NoWeb:
      Enabled: true
      NoWeb#1:
        Enabled: true
    ClonedMovements:
      Enabled: true
      ClonedMovement#1:
        Enabled: true
    FastClimb:
      Enabled: true
      FastClimb#1:
        Enabled: true
  Combat:
    Enabled: true
    HighCPS:
      Enabled: false
      HighCPS#1:
        Enabled: false
      HighCPS#3:
        Enabled: false
      HighCPS#2:
        Enabled: false
    AutoClicker:
      Enabled: true
      AutoClicker#1:
        Enabled: true
    AntiKB:
      Enabled: true
      AntiKB#1:
        Enabled: true
    AutoArmor:
      Enabled: true
      AutoArmor#1:
        Enabled: true
    KillAura:
      Enabled: true
      KillAura#3:
        Enabled: true
      KillAura#5:
        Enabled: true
      KillAura#2:
        Enabled: true
      KillAura#4:
        Enabled: true
      KillAura#1:
        Enabled: true
    FastBow:
      Enabled: true
      FastBow#1:
        Enabled: true
  Player:
    Enabled: true
    NoFall:
      Enabled: true
      NoFall#1:
        Enabled: true
      NoFall#2:
        Enabled: true
    AutoTool:
      Enabled: true
      AutoTool#1:
        Enabled: true
    GhostHand:
      Enabled: true
      GhostHand#1:
        Enabled: true
    SafeWalk:
      Enabled: true
      SafeWalk#1:
        Enabled: true
    AntiFire:
      Enabled: true
      AntiFire#1:
        Enabled: true
    FastEat:
      Enabled: true
      FastEat#1:
        Enabled: true
    SelfHarm:
      Enabled: true
      SelfHarm#1:
        Enabled: true
    Zoot:
      Enabled: true
      Zoot#1:
        Enabled: true
    HealthTag:
      Enabled: true
      HealthTag#1:
        Enabled: true
  World:
    Enabled: true
    Scaffold:
      Enabled: true
      Scaffold#3:
        Enabled: true
      Scaffold#1:
        Enabled: true
      Scaffold#2:
        Enabled: true
    AutoBuild:
      Enabled: true
      AutoBuild#1:
        Enabled: true
    IllegalBlockPlace:
      Enabled: true
      IllegalBlockPlace#1:
        Enabled: true
    FastBreak:
      Enabled: false
      FastBreak#1:
        Enabled: false
    IllegalBlockBreak:
      Enabled: true
      IllegalBlockBreak#1:
        Enabled: true
        `

**Comment by steviebeenz** [comment]
Please use paste.md-5.net, a Github gist or another pastebin service.

**Comment by MSWS** [comment]
Does the **server crash** or a player get kicked? Also, does this happen without ProtocolLib?
