### ISSUE TITLE
FastBreak bug

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#22]
**What server version are you running?**
Spigot 1.15.2

**What Minecraft Client Version are you running?**
1.15.2 Optifne

**What version of NOPE are you running?**
The last of your server

**What is the debug ID?**
![2020-05-13_15 34 06](https://user-images.githubusercontent.com/39565971/81819212-4f05c080-952f-11ea-9f61-5256f057f762.png)

**Is there any debug information? (Please include average info if available)**
![2020-05-13_15 34 09](https://user-images.githubusercontent.com/39565971/81819229-54630b00-952f-11ea-811f-0bdb7c97a6a1.png)
![2020-05-13_15 35 16](https://user-images.githubusercontent.com/39565971/81819273-62189080-952f-11ea-8657-6e6118547635.png)
![2020-05-13_15 35 24](https://user-images.githubusercontent.com/39565971/81819277-63e25400-952f-11ea-9682-6bc88642c36c.png)

**What is causing this false flag?**
When i break a leaves

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
Nop

**Comment by MSWS** [comment]
This has been found already and will be fixed in 1.2.9.
