### ISSUE TITLE
Sweet Berries

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#23]
**What server version are you running?**
1.15.2

**What Minecraft Client Version are you running?**
1.15.2 Optifine

**What version of NOPE are you running?**
The last of your server

**What is the debug ID?**
![2020-05-13_15 38 07](https://user-images.githubusercontent.com/39565971/81819553-c0457380-952f-11ea-8c1a-d9e9d9b0f2f9.png)

**Is there any debug information? (Please include average info if available)**
![2020-05-13_15 37 32](https://user-images.githubusercontent.com/39565971/81819599-ca677200-952f-11ea-91a6-b6f1ab4ce7b9.png)
![2020-05-13_15 37 28](https://user-images.githubusercontent.com/39565971/81819641-d6ebca80-952f-11ea-8f1a-5e47eaae76b1.png)
![2020-05-13_15 37 29](https://user-images.githubusercontent.com/39565971/81819660-df440580-952f-11ea-8861-d6a7a2604468.png)
![2020-05-13_15 37 31](https://user-images.githubusercontent.com/39565971/81819669-e66b1380-952f-11ea-939a-5aa73a91bd7b.png)

**What is causing this false flag?**
I jump on a Sweet Berries plant (Only the little i think)

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
No

**Comment by MSWS** [comment]
Patched in 1.2.9.
