### ISSUE TITLE
Step Stairs

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#24]
**What server version are you running?**
1.15.2

**What Minecraft Client Version are you running?**
1.15.2 optifne

**What version of NOPE are you running?**
Last Server

**What is the debug ID?**
![2020-05-13_15 44 37](https://user-images.githubusercontent.com/39565971/81820312-c0923e80-9530-11ea-9d41-1772d5ac8bd8.png)

**Is there any debug information? (Please include average info if available)**
![2020-05-13_15 44 31](https://user-images.githubusercontent.com/39565971/81820323-c6881f80-9530-11ea-955a-95b607930042.png)
![2020-05-13_15 45 49](https://user-images.githubusercontent.com/39565971/81820372-d30c7800-9530-11ea-8683-16901280e16a.png)

**What is causing this false flag?**
Down stairs 

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
No

**Comment by Neiy0** [comment]
And if i am on a block and break him, i have an alert 

![2020-05-13_15 48 04](https://user-images.githubusercontent.com/39565971/81820629-2383d580-9531-11ea-8728-72392047a289.png)
![2020-05-13_15 48 27](https://user-images.githubusercontent.com/39565971/81820662-33031e80-9531-11ea-89eb-c2abc2d5c25a.png)

**Comment by MSWS** [comment]
Thank you. In the future please provide more details. Simply saying "down stairs" is fairly vague.
