### ISSUE TITLE
Step of the dead

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#25]
**What server version are you running?**
1.15.2

**What Minecraft Client Version are you running?**
1.15.2 Optifine

**What version of NOPE are you running?**
Your server 

**What is the debug ID?**
![2020-05-13_16 16 53](https://user-images.githubusercontent.com/39565971/81824091-6051cb80-9535-11ea-91ff-c18bb24db0a6.png)

**Is there any debug information? (Please include average info if available)**
![2020-05-13_16 16 53](https://user-images.githubusercontent.com/39565971/81824143-6d6eba80-9535-11ea-8d8c-eb3959712020.png)
![2020-05-13_16 18 42](https://user-images.githubusercontent.com/39565971/81824183-7495c880-9535-11ea-8015-57f7fbade6d7.png)

**What is causing this false flag?**
When i jump on a block and i go back down 

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
No

**Comment by Neiy0** [comment]
And if I’m on a stair and I go down, I always get the alert

![2020-05-13_16 21 21](https://user-images.githubusercontent.com/39565971/81824464-cb030700-9535-11ea-8e18-1f1ced538cc9.png)

**Comment by Neiy0** [comment]
Idk for Jesus but okey xD, it's the water but I didn’t go on it

![2020-05-13_16 22 32](https://user-images.githubusercontent.com/39565971/81824599-f4239780-9535-11ea-8416-a8755b2354c6.png)

![2020-05-13_16 23 21](https://user-images.githubusercontent.com/39565971/81824702-11f0fc80-9536-11ea-8207-a9d3f50e53d3.png)

**Comment by MSWS** [comment]
Should be patched in 1.2.11.
