### ISSUE TITLE
Spider and Nofall and Jesus and Glide not getting triggered

### ISSUE THREAD

**Issue by BlazenBoi** [MSWS/NOPE#26]
**What server version are you running?**
1.15.2 Spigot inside of Bungee
**What version of NOPE are you running?**
1.2.11
**What is the bug?**
whenever I activate spider and nofall and jesus and glide on my wurst test client it doesn't pick it up on nope
**Is there anything else to add?**
No Error logs, and when you step on pressure plates it counts you as high cps and also when you eat steak while climbing vines.

**Comment by MSWS** [comment]
It looks like the combination of NoFall and Glide lead to an unintended bypass, I will look further into this. Thank you for reporting it!

**Comment by MSWS** [comment]
The BHop check should now cover this. It is a patchwork job and I will look into it later but for now I am closing this issue.

**Comment by MSWS** [comment]
After an inspection into the code I realized there was an error with the Glide check. This should now be patched.
