### ISSUE TITLE
Add Pastebin Support

### ISSUE THREAD

**Issue by MSWS** [MSWS/NOPE#27]
Add pastebin support for the server to auto-upload logs to pastebin. The user would have to define their own pastebin developer key.

**Comment by Kas-2** [comment]
Addition: Make it interchangable between Hastebin(maybe even custom hastebins!!!) and pastebin, or nothing.

**Comment by MSWS** [comment]
> Addition: Make it interchangable between Hastebin(maybe even custom hastebins!!!) and pastebin, or nothing.

Hastebin is much easier to integrate so for now I will keep it at hastebin.

Added in 1.2.13.

**Comment by Kas-2** [comment]
@MSWS Custom Hastebins have the same API(if not tampered with), and are as easy to implement as hastebin itself...

**Comment by MSWS** [comment]
> @MSWS Custom Hastebins have the same API(if not tampered with), and are as easy to implement as hastebin itself...

I have disabled hastebin support and will look into readding them in the future.

**Comment by MSWS** [comment]
Should now be fixed in 1.4.3.
