### ISSUE TITLE
Blaze and blocks not removing for players getting banned

### ISSUE THREAD

**Issue by HotelMakar** [MSWS/NOPE#3]
Sometimes the blaze and blocks dont remove and when the players get banned the blaze stays there and sometimes it removes the block that is overwritten by the beacons and obsidians and it becomes air

**Comment by MSWS** [comment]
What server version are you using?

**Comment by HotelMakar** [comment]
1.8.8 spigot

**Comment by MSWS** [comment]
Can not replicate. Please try completely /restart ing your server.

What version of NOPE are you running?
