### ISSUE TITLE
Jump slime block

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#31]
**What server version are you running?**
1.15.2

**What Minecraft Client Version are you running?**
1.15.2 Optifine

**What version of NOPE are you running?**
Your server

**What is the debug ID?**
I can't active it xD

**Is there any debug information? (Please include average info if available)**
I can't active it too

**What is causing this false flag?**
When i jump on slime block like here
![2020-05-17_17 58 06](https://user-images.githubusercontent.com/39565971/82153579-8b575a80-9868-11ea-8f50-a6d1e1d44ee2.png)

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
Nop

**Comment by MSWS** [comment]
I will look into this.

**Comment by MSWS** [comment]
This is patched in 1.3.1.
