### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by dogeydoggo** [MSWS/NOPE#32]
**What server version are you running?**
I am running Minecraft 1.15.2 and using Spigot.

**What Minecraft Client Version are you running?**
I am running tlauncher 2.68

**What version of NOPE are you running?**
I am using the latest version.

**What is the debug ID?**
I have already removed the plugin from my server.

**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_

**What is causing this false flag?**
I had the latest version of NOPE and I also had a plugin that broke the whole tree when a log was chopped. When I tested if they would work together, I was banned for 1 week without warning.

**Is this false flag reproducible on the test server?**
No.

**Is there anything else to add?**
I am new to making servers and plugins and it says to put in this token when appealing: JC8BO8AQSYBSK77Q

**Comment by MSWS** [comment]
So no, it’s not compatible.

**Comment by dogeydoggo** [comment]
How do I get rid of the ban then?

**Comment by MSWS** [comment]
It's your server, NOPE automatically hooks into any ban plugins. You can try /unban [name] or /pardon [name]

**Comment by dogeydoggo** [comment]
Ok, i will reinstall nope and let you know what happens.

**Comment by dogeydoggo** [comment]
The /pardon [name] worked. Thank for the help!

Have a nice day!
