### ISSUE TITLE
FastSneak

### ISSUE THREAD

**Issue by Neiy0** [MSWS/NOPE#33]
**What server version are you running?**
1.15.2

**What Minecraft Client Version are you running?**
1.15.2 Optifine

**What version of NOPE are you running?**
Your server

**What is the debug ID?**
I can't upload image idk why, go here
https://www.noelshack.com/2020-21-2-1589874249-2020-05-19-09-39-47.jpg

**Is there any debug information? (Please include average info if available)**
I can't upload image idk why, go 
here https://www.noelshack.com/2020-21-2-1589874172-2020-05-19-09-40-14.jpg 
https://www.noelshack.com/2020-21-2-1589874222-2020-05-19-09-40-13.jpg
https://www.noelshack.com/2020-21-2-1589874266-2020-05-19-09-38-56.jpg

**What is causing this false flag?**
I sneak unsneak for bridge

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
No

**Comment by MSWS** [comment]
This has been patched in 1.3.1.
