### ISSUE TITLE
I was banned on a server I was setting up and cant unban myself

### ISSUE THREAD

**Issue by hon225** [MSWS/NOPE#34]
**What server version are you running?**
1.15.2

**What version of NOPE are you running?**
The latest as of today

**What is the bug?**
I got banned on a server I was setting up testing the anti-cheat and now I can't unban myself. I have tried everything running thee commands in-game and deleting and installing the anti-cheat back onto the server. 

**Is there anything else to add?**
it says to send this ban appel token in
1SHTOJ1AEMCOCV72

**Comment by hon225** [comment]
Okay I fixed it I had to go into the server bans manually and unban myself

**Comment by MSWS** [comment]
NOPE hooks into any ban plugin. If you have a ban plugin I expect you to know the unban command. If you host your own server I expect you to know how to unban yourself from a vanilla minecraft ban. /pardon (name)
