### ISSUE TITLE
False Positive with ladders climbing

### ISSUE THREAD

**Issue by obsessivecoder1** [MSWS/NOPE#35]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.15 Paper version git-Paper-299 (MC: 1.15.2)
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.3.2
**What is the bug?**
_Please be descriptive_
When players are climbing the ladder, the anticheat thinks they are fast climbing soon after they would get banned 
**Is there anything else to add?**
_Are there any error logs?_
None at all

**Comment by MSWS** [comment]
Please re-open a new issue using the False Flag template.
