### ISSUE TITLE
"/trigger" command does not work properly

### ISSUE THREAD

**Issue by cs127** [MSWS/NOPE#36]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Minecraft 1.15.2, Paper/Spigot

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.3.4

**What is the bug?**
_Please be descriptive_
When the NOPE plugin is installed, it prevents the `/trigger` command from working properly. Attempting to run a trigger will output `You cannot trigger this objective yet`. This problem doesn't occur when the NOPE plugin is not in the plugins folder.

**Is there anything else to add?**
_Are there any error logs?_
No.

**Comment by MSWS** [comment]
I was unable to replicate this. Please try clearing all scoreboard objectives and reinstalling NOPE.
