### ISSUE TITLE
ChestStealer triggers on shift double click.

### ISSUE THREAD

**Issue by AKSizov** [MSWS/NOPE#37]
**What server version are you running?**
1.15.2 Paper Spigot

**What Minecraft Client Version are you running?**
1.15.2 Vanilla

**What version of NOPE are you running?**
1.4.2.1

**What is the debug ID?**
ChestStealer#1

**Is there any debug information? (Please include average info if available)**
It flags people well over 1000, and triggers an instant ban.

**What is causing this false flag?**
There is a quick loot keybind in vanilla minecraft, hold an item and then shift double click on another one. It instantly loots all of the same item. Doing this loots multiple slots at once, and therefore triggers ChestStealer. 
It only steals the exact same item however, so it will never loot a different item.

**Is this false flag reproducible on the test server?**
Yes.

**Is there anything else to add?**
This might be able to be fixed by checking if the items stolen are all the exact same type.

**Comment by MSWS** [comment]
Thank you for mentioning the same ItemStack rule, I will implement this in the next version.

**Comment by AKSizov** [comment]
No problem, thanks for the quick response!

**Comment by MSWS** [comment]
I have removed ChestStealer for now, the logic seems excessively complicated.
