### ISSUE TITLE
Flagged for speed when jumping down into water

### ISSUE THREAD

**Issue by KevinDaGame** [MSWS/NOPE#38]
**What server version are you running?**
version git-Spigot-2f5d615-d07a78b (MC: 1.15.2)
**What Minecraft Client Version are you running?**
1.15.2
**What version of NOPE are you running?**
1.4.3

**What is the debug ID?**
Speed#2
Jesus#3 when swimming back up

**Is there any debug information? (Please include average info if available)**
Speed#2: Dist: 1.0472570156359349 >= .7
Jesus#3: Average: 4.2929088393199635
AVD: 2.4707247672629946
**What is causing this false flag?**
I think it might have something to do with the system not properly recognizing that I have landed in water and thinks I might be still falling which somehow triggers jesus

**Is this false flag reproducible on the test server?**
yes, jumping of the tower with vines into the water pool, although this is not deep enough to trigger the Jesus too

**Is there anything else to add?**

**Comment by MSWS** [comment]
This has been patched in the next update. Thanks for reporting it!
