### ISSUE TITLE
Falling over water triggers jesus flag

### ISSUE THREAD

**Issue by KevinDaGame** [MSWS/NOPE#39]
What server version are you running?
version git-Spigot-2f5d615-d07a78b (MC: 1.15.2)
What Minecraft Client Version are you running?
1.15.2
What version of NOPE are you running?
1.4.3

**What is the debug ID?**
jesus#3

**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_
![image](https://user-images.githubusercontent.com/65958288/82905657-6c418280-9f64-11ea-8a34-39b09fb903ca.png)

**What is causing this false flag?**
Falling over water makes the anticheat think I am above water and not going in it I think.

**Is this false flag reproducible on the test server?**
Yes, jumping of the giant ice disk in the sky into the glass box full of water triggers it when you are above it

**Is there anything else to add?**

**Comment by MSWS** [comment]
This is now patched in the next version. Thank you for reporting it.
