### ISSUE TITLE
Blase and block not disappearing

### ISSUE THREAD

**Issue by Wolffy821** [MSWS/NOPE#4]
When the system detected that the player is cheating, the blaze and block will appear around him. And once it appeared and the player left the server, the blaze and the block will still be there and not disappear.

**Comment by MSWS** [comment]
Please create a new issue using the proper Bug Reporting format. 

**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_

**What is the bug?**
_Please be descriptive_

**Is there anything else to add?**
