### ISSUE TITLE
Standing slightly outside of water triggers Glide#1, Flight#4, Flight#3, Flight#2, Flight#1, Spider#1

### ISSUE THREAD

**Issue by AKSizov** [MSWS/NOPE#40]
**What server version are you running?**
Paper Spigot 1.15.2

**What Minecraft Client Version are you running?**
Vanilla 1.15.2

**What version of NOPE are you running?**
1.4.3

**What is the debug ID?**
Glide#1, Flight#4, Flight#3, Flight#2, Flight#1, Spider#1

**What is causing this false flag?**
Standing on "the edge" of water causes the AC to think you are flying.

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
There is an image attached below to show what I mean by "standing on the edge of water"
![image](https://user-images.githubusercontent.com/37084670/82918006-21167800-9f42-11ea-8d78-42d1424fc35c.png)

**Comment by MSWS** [comment]
This was patched in 1.4.4. Thank you for reporting it.
