### ISSUE TITLE
NoSwing#1 Flags when trying to place into occupied block

### ISSUE THREAD

**Issue by AKSizov** [MSWS/NOPE#41]
**What server version are you running?**
Paper Spigot 1.15.2

**What Minecraft Client Version are you running?**
Vanilla 1.15.2

**What version of NOPE are you running?**
Nope 1.4.4

**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like NoSwing#1

**What is causing this false flag?**
Attempting to place something in an occupied slot triggers the flag. 
This happens when you place on the side of a non-whole block, such as a torch, lantern or slab.

**Is this false flag reproducible on the test server?**
Yes

**Is there anything else to add?**
![Invalid_position](https://user-images.githubusercontent.com/37084670/83017001-ddc71280-9ff0-11ea-8db4-374e4b6b95b4.png)

**Comment by MSWS** [comment]
This has already been patched I simply haven’t released it yet. Thanks for the report!
