### ISSUE TITLE
While Swimming/Wading in water Glide and Flight flags are set off.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#42]
**What server version are you running?**
Paper Spigot 1.15.2 Latest

**What Minecraft Client Version are you running?**
Vanilla 1.15.2
**What version of NOPE are you running?**
1.15.1

**What is the debug ID?**
Flight#4
Glide#1
Flight#1

**Is there any debug information? (Please include average info if available)**
See GIF IMG attached below.
https://gyazo.com/fd07adf40d44038c10668ca97969d109

**What is causing this false flag?**
Swimming/Wading

**Is this false flag reproducible on the test server?**
_MSWS.xyz is the IP_
Not that I can see.

**Is there anything else to add?**
The flags seem to be random, but when one occurs a plethora flood the chat.

**Comment by MSWS** [comment]
I was unable to replicate, please provide more details and perhaps a gif of you false flagging.
