### ISSUE TITLE
"Task #20 for NOPE v1.5.1 generated an exception" breaking kick

### ISSUE THREAD

**Issue by vastolf** [MSWS/NOPE#43]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Latest Paper-Spigot 

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.5.1

**What is the bug?**
_Please be descriptive_
I'm getting the following console error:
```
01.06 20:21:14 [Server] WARN [NOPE] Task #17 for NOPE v1.5.1 generated an exception
01.06 20:21:14 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class xyz.msws.anticheat.protocols.WrapperPlayServerSetSlot
01.06 20:21:14 [Server] INFO at xyz.msws.anticheat.checks.combat.AutoArmor1$1.run(AutoArmor1.java:77) ~[?:?]
01.06 20:21:14 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:21:14 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:21:14 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:21:14 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:21:14 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:21:14 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:21:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
I am testing in a new world. I have a main world where hacks are enabled and have given the `nope.bypass.*` wildcard permission to True for the default group in the main world Context & it's end and nether worlds as well (using LuckPerms). Players are not getting kicked for hacking in those worlds (which is good).

I've created a new world that will work as a new dimension that does NOT allow hacks. I've set the `nope.bypass.*` wildcard permission to False for this new world. I log in and try flying; I have set up an Action for flight:
```
Flight:
- 'basiclog|vl>500|instakick|vl>800'

...
...
...

Commands:
   instakick: 'kick:You were instantly kicked'
```

The first time I try to fly, it kicks me (which is what I want). But when I re-connect and start flying again, I can see it logging Flight check fails (which again, is good) but it doesn't kick me again. As you can see my instakick command has no delay. I'm thinking it has to do with this error that I posted above, as that error appears when it kicks me the first time.

**Is there anything else to add?**
_Are there any error logs?_
**Here is where it detects me flying the first time:**
01.06 20:36:39 [Server] INFO [INFO] DanniloSN failed Flight#2

**Here is the error**
01.06 20:36:43 [Server] WARN [NOPE] Task #20 for NOPE v1.5.1 generated an exception
01.06 20:36:43 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class xyz.msws.anticheat.protocols.WrapperPlayServerSetSlot
01.06 20:36:43 [Server] INFO at xyz.msws.anticheat.checks.combat.AutoArmor1$1.run(AutoArmor1.java:77) ~[?:?]
01.06 20:36:43 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:36:43 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:36:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:36:43 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:36:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:36:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-307]
01.06 20:36:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Here it is catching me flying with speed hacks again, but it doesn't kick me**
01.06 20:36:44 [Server] INFO [INFO] DanniloSN failed Speed#1
01.06 20:36:49 [Server] INFO [INFO] DanniloSN failed Speed#1

**Comment by MSWS** [comment]
Please try completely restarting your server and check if this issue persists.

**Comment by vastolf** [comment]
@msws I've restarted multiple times and am still getting the error

**Comment by MSWS** [comment]
I will look into it, thank you.

**Comment by vastolf** [comment]
@MSWS thank you!

**Comment by vastolf** [comment]
@MSWS is it potentially because I don't have Protocol lib installed? The documentation says installing it is "recommended" so I assumed it wasn't mandatory.

**Comment by MSWS** [comment]
> @MSWS is it potentially because I don't have Protocol lib installed? The documentation says installing it is "recommended" so I assumed it wasn't mandatory.

Yes that’s probably it. I’ll have to update the check to not enable unless protocol lib is enabled. On a similar note you definitely should install ProtocolLib either way.

**Comment by MSWS** [comment]
This should be fixed in 1.5.2.

**Comment by vastolf** [comment]
@MSWS oh you've released an update? Great thank you so much :). I'm not really sure from the Docs what the benefits are of installing Protocol Lib

**Comment by MSWS** [comment]
> @MSWS oh you've released an update? Great thank you so much :). I'm not really sure from the Docs what the benefits are of installing Protocol Lib

The following checks rely on ProtocolLib:
NoSlowDown#5
SkinBlinker#1
NoSwing#1
Timer#2
AutoArmo#1

**Comment by vastolf** [comment]
Okay thank you sir, really appreciate it!
