### ISSUE TITLE
Could not pass event PlayerMoveEvent to NOPE v1.5.2

### ISSUE THREAD

**Issue by Seff300** [MSWS/NOPE#44]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper 1.15.2

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.5.2

**What is the bug?**
_Please be descriptive_
When I was testing NOPE I got the following error in my console (See down below). Also this doesn't always happen but sometimes it randomly starts giving this error.

**Is there anything else to add?**
_Are there any error logs?_
https://pastebin.com/5B6QYdxk

**Comment by MSWS** [comment]
Have you tried restarting the server completely?

**Comment by MSWS** [comment]
I will be closing this issue for now, if it is still happening after a restart please let me know.
