### ISSUE TITLE
GhostHand#1

### ISSUE THREAD

**Issue by Seff300** [MSWS/NOPE#47]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper 1.15.2

**What Minecraft Client Version are you running?**
1.15.2

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.5.4

**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_
Seff300 failed GhostHand#1

**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_

**What is causing this false flag?**
_What exactly are you doing that causes a false flag?_
Trying to open a chest that was in a WorldGuard protected region

**Is this false flag reproducible on the test server?**
_MSWS.xyz is the IP_
I don't know

**Is there anything else to add?**
No

**Comment by MSWS** [comment]
Does this happen without WorldGuard?
