### ISSUE TITLE
Nope getting bugged like loads

### ISSUE THREAD

**Issue by obsessivecoder1** [MSWS/NOPE#48]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper version git-Paper-162 (MC: 1.15.2)
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.5.4
**What is the bug?**
_Please be descriptive_
When I had installed the new update, Console did not like it, most checks had not worked, and console was spewing errors
**Is there anything else to add?**
_Are there any error logs?_
[latest (2).log](https://github.com/MSWS/NOPE/files/4739798/latest.2.log)

**Comment by MSWS** [comment]
This should be fixed in 1.6. Thanks for the report. For future reference please **do not** upload log files, you should only be uploading the error logs and if they’re long then upload them to pastebin or equivalent.
