### ISSUE TITLE
[FEATURE] Token Checking

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#49]
I was wondering if you are planning in implementing something like /nope token <token> that would return the name of the player, which checks they failed and to what vl.

**Comment by MSWS** [comment]
This is an interesting idea, I will add this in the next update.

**Comment by steviebeenz** [comment]
Thanks.

**Comment by MSWS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [/nope lookup](https://trello.com/c/pglJaTNs/133-nope-lookup)

**Comment by MSWS** [comment]
I have completed this and it will be added in 1.6.
