### ISSUE TITLE
Blase and Block not Disappearing

### ISSUE THREAD

**Issue by Wolffy821** [MSWS/NOPE#5]
**What server version are you running?**
Spigot 1.8.8
**What version of NOPE are you running?**
1.1

**What is the bug?**
When the system detected that the player is cheating, the blaze and the block will appear. And once it appeared and the player left the server, the blaze and the block will still be there and not disappear.

**Comment by MSWS** [comment]
Fixed this bug in 1.1.5, apologies for not figuring i tout sooner.
