### ISSUE TITLE
SUGGESTION] Banwave hook for Paper

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#53]
You know that Flying is not allowed paper kick?
Potentially make a Banwave hook for that?

**Comment by MSWS** [comment]
The vanilla flying is not allowed kick is unreliable. What exactly do you mean by adding a banwave hook for it?

**Comment by steviebeenz** [comment]
So it would add the player to the Banwave.

**Comment by MSWS** [comment]
I will not be adding additional support for the vanilla "anticheat", the flying check is very unreliable.
