### ISSUE TITLE
Discord Link Broken. 

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#59]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Github Web Client 

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
Latest Master. 
**What is the bug?**
_Please be descriptive_
The Discord link in the wiki is broken. 
**Is there anything else to add?**
_Are there any error logs?_
Add https:// to the start of it.

**Comment by steviebeenz** [comment]
This is for the wiki.

**Comment by MSWS** [comment]
This should be fixed, thanks for letting me know.
