### ISSUE TITLE
List of False Flags

### ISSUE THREAD

**Issue by CaptainObvious0** [MSWS/NOPE#6]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
PaperSpigot 1.12.2

**What Minecraft Client Version are you running?**
Optifine 1.12.2

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
v1.1

**What is causing this false flag?**
_What exactly are you doing that causes a false flag?_
**Is there anything else to add?**

**(IllegalBlockPlace#1)**
Placing lilypads on water will flag 

**(Scaffold#2 Diff: Range between 42.42 -> 69.42)**
Placing ladders on blocks

**(Scaffold#3) + (Flight#1) + (Flight#4 - Jumping - Dist: Increases over time YDiff: -0.18 <-> -1.06
) + (Step#1 - Diff: 0.0625)**
Placing/Moving/Jumping on carpets (Possibly other blocks with different block margins) 
Moving/Jumping on soil (Dirt mined by hoe)

**(FastClimb#1 - Diff: -0.126, -0.072)**
Jumping onto a ladder from the ground

**(Flight#4 - Dist: 38.92 <-> 47.78 YDiff: -1.39 <-> -2.87)**
Jumping while on a horse but it does not flag when the player has jump boost applied

**(FastSneak#1 - Avg: 0.122 <-> 0.128 Size: 32 <-> 40)**
Just tapping shift a somewhat quickly will flag. Flags faster if the player is moving.

**(Zoot#1)**
Flags for using /heal (Essentials, other plugins may flag too) while a potion is applied

**(Timer#1 Avg: 0.94 <-> 3.38 Current: 7<-> 10)**
Randomly flags while being on the server. No particular way to reproduce. 

**(FastSneak#1 - Avg: 0.16 (max) Size: 32 <-> 40)**
Sprinting then sneaking on ice

Etc Issue:
- Ban message does not match up with banwaves file.

**Comment by MSWS** [comment]
Thank you for your report. I will resolve a few of these issues, however certain checks (eg: Zoot) will not be patched.

**Comment by MSWS** [comment]
Several issues have been resolved. Further testing is needed for other issues. I am going to close this issue as I am now aware of the false flags. Thank you for reporting them!
