### ISSUE TITLE
Discord Link Broken 

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#60]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Github Web
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
Latest Master
**What is the bug?**
_Please be descriptive_
Discord link broken in readme.md
**Is there anything else to add?**
_Are there any error logs?_
Merge my PR to fix.

**Comment by MSWS** [comment]
There is no (free) API for AdminBans, if you know otherwise please let me know.

**Comment by MSWS** [comment]
Resolved, thanks for the PR.
