### ISSUE TITLE
Integrations 

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#61]
**Is your feature request related to a problem/bug?**
Kinda, yes. 

**Describe the solution you'd like**
I just want this to integrate with other anticheat software to add where they would usually kick, make them add to Banwave. 

**Have you tried implementing this solution alternatively?**
Yes, but some acs have an api and a bad config 

**Additional context**
Add any other context or screenshots about the recommendation please put here.

It would make my and a lot of others lives easier... Potentially make them separate addons to prevent having a massive code base.

**Comment by MSWS** [comment]
NOPE is intended as a standalone anti-cheat, I will not be adding support for other anti-cheats as that would negate the point of this one.
