### ISSUE TITLE
Adminbans

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#62]
**Is your feature request related to a problem/bug?**
No

**Describe the solution you'd like**
Adminbans plugin hook

**Have you tried implementing this solution alternatively?**
Yes, it worked, but I would like to see it natively supported. 

**Additional context**
Add any other context or screenshots about the recommendation please put here.
I think this is an amazing small plugin providing an alternative to all other ban plugins with an epic UI.

**Comment by MSWS** [comment]
There is no (free) API for AdminBans, if you know otherwise please let me know.
