### ISSUE TITLE
Github Projects

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#64]
**Is your feature request related to a problem/bug?*
NOPE

**Describe the solution you'd like**
I would like to see your trello borak moved to Gh projects

**Have you tried implementing this solution alternatively?**
NOPE 

**Additional context**
Add any other context or screenshots about the recommendation please put here.

This would allow better visibility into the roadmap and what will be released per release etc.

**Comment by MSWS** [comment]
I personally prefer Trello, it supports draging cards and has a nicer UI. I will be keeping this project on Trello.
