### ISSUE TITLE
Save yourself some time

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#65]
**Is your feature request related to a problem/bug?**
No

**Describe the solution you'd like**
Label new accepted suggestions YEP 

**Have you tried implementing this solution alternatively?**
NOPE

**Additional context**
Add any other context or screenshots about the recommendation please put here.

Save your self some time.

**Comment by steviebeenz** [comment]
So you won't have to type YEP

**Comment by MSWS** [comment]
I won't be assigning all accepted suggestions as anything, they'll simply be closed.
