### ISSUE TITLE
Tell us Which Release

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#66]
**Is your feature request related to a problem/bug?**
NOPE

**Describe the solution you'd like**
Label accepted issues with the versions they will be released in

**Have you tried implementing this solution alternatively?**
NOPE

**Additional context**
Add any other context or screenshots about the recommendation please put here.
NOPE

**Comment by MSWS** [comment]
I will make sure to specify what version will fix the issue. I don't want to have a dozen labels just for versions.
