### ISSUE TITLE
Public Trello Board

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#67]
**Is your feature request related to a problem/bug?**
NOPE 

**Describe the solution you'd like**
We want to see the roadmap. 

**Have you tried implementing this solution alternatively?**

NOPE

**Additional context**
Add any other context or screenshots about the recommendation please put here.

Potentially share the link to view your trello?

**Comment by MSWS** [comment]
https://github.com/MSWS/NOPE/commit/9ca1b6e2f80f839c376fc2116e099fdcb51b167d

Added
