### ISSUE TITLE
Potential Banwave Issue

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#68]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper 1.15

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
Latest (I freshly downloaded for this bug report to check it wasnt patched) 

**What is the bug?**
_Please be descriptive_
A small bug that when you add a player to Banwave it doesn't display on scoreboard. 

**Is there anything else to add?**
_Are there any error logs?_

**to be added, I will check. **

**Comment by MSWS** [comment]
The Banwaves command hasn’t been updated yet. I’ve already fixed it and it will be pushed with 1.6
