### ISSUE TITLE
Chest Stealer

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#70]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_

Paper 1.15

**What Minecraft Client Version are you running?**

It doesn't matter

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_

Latest

**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_

There is none 

**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_

No

**What is causing this false flag?**
_What exactly are you doing that causes a false flag?_

Coz there's no Cheat Stealer Check. 

**Is this false flag reproducible on the test server?**
_MSWS.xyz is the IP_
Yes

**Is there anything else to add?**

Please add a Chest Stealer Check.

**Comment by MSWS** [comment]
This isn't a false flag, why did you report a non-false flag.
