### ISSUE TITLE
Ban Compat

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#77]
**Is your feature request related to a problem/bug?**
No

**Describe the solution you'd like**
Ban Compat 

**Have you tried implementing this solution alternatively?**

**Additional context**
Add any other context or screenshots about the recommendation please put here.

For the Vanilla Bans, EssentialsX Bans, Ban Manager, Potentially even an integrated ban manager or a native ban manager addon... Optional extra so no lag...

**Comment by MSWS** [comment]
Please be more descriptive in what you want. NOPE by default has a native ban hook that hooks into the Minecraft ban list, this by extension means it automatically hooks into essentials' ban system.

**Comment by steviebeenz** [comment]
A native ban addon for the plugin.
For those small servers with no ban plugin. Like  tiny single gamemode servers.

**Comment by MSWS** [comment]
There is already a native ban plugin.

**Comment by steviebeenz** [comment]
Even maybe a whitelist removal feature for those tiny servers.

**Comment by MSWS** [comment]
> Even maybe a whitelist removal feature for those tiny servers.

This is also possible with the custom commands.
