### ISSUE TITLE
FastEat/NoSlow/Eat Hacks

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#78]
**Is your feature request related to a problem/bug?**
No

**Describe the solution you'd like**
Eat Hacks like NoSlow, FastEat, Regen etc. 

**Have you tried implementing this solution alternatively?**
NOPE

**Additional context**
Add any other context or screenshots about the recommendation please put here.

NOPE

**Comment by MSWS** [comment]
NoSlow and FastEat already have checks, regen does not work on 1.15.

**Comment by steviebeenz** [comment]
Yeah, Regen works in 1.15 but differently. Through Ghost Items and gapples.

**Comment by MSWS** [comment]
If there is a free client that has fast eat I will look into it.
