### ISSUE TITLE
Minetinker Hook

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#80]
**Is your feature request related to a problem/bug?**
Yes. 

**Describe the solution you'd like**
Add compat for MineTinker

**Have you tried implementing this solution alternatively?**
No
**Additional context**
Add any other context or screenshots about the recommendation please put here.

**Comment by MSWS** [comment]
Please take more time in these suggestions. [You should be linking the plugin](https://www.spigotmc.org/resources/minetinker-50-modifiers-tools-and-armor.58940/). For now go ahead and report any false flags that occur with the plugin.

**Comment by MSWS** [comment]
I will be closing this issue, report any false flags as such.
