### ISSUE TITLE
Trident with riptide Enchanting

### ISSUE THREAD

**Issue by NG-Ting** [MSWS/NOPE#82]
**What server version are you running?**
Paper Spigot 1.15.2

**What Minecraft Client Version are you running?**
Vanilla 1.15.2

**What version of NOPE are you running?**
1.5.4

**What is the debug ID?**
Glide#1
Timer#2
Flight#4
SafeWalk#1

**Is there any debug information? (Please include average info if available)**
[DEV] NG_Ting failed Glide#1 +171 (Avg : -1.2392861313419672)
[DEV] NG_Ting failed Glide#1 +117 (Avg: -0.14918482477502834)
[DEV] NG_Ting failed Timer#2 +0 (Avg: 49.94)
[DEV] NG_Ting failed Timer#2 +0 (Avg: 49.92)
[DEV] NG_Ting failed Timer#2 +0 (Avg: 49.92)

[DEV] NG_Ting failed Flight#4 +50
(Dist: 1104.7402594207813 >= 10
YDiff: -27.147041326622144 < 0)

[DEV] NG_Ting failed SafeWalk#1 +5
(Yaw: 32.193954
dX: 0.108147
dZ: 0.00
Blocks: Air Air Air Air Air Air Air Air Air )

[DEV] NG_Ting failed SafeWalk#1 +5
(Yaw: 42.693970
dX: 0.111705
dZ: 0.00
Blocks: Air Air Air Air Air Air Air Air Air )

[DEV] NG_Ting failed SafeWalk#1 +5
(Yaw: 37.256035
dX: 0.117252
dZ: 0.00
Blocks: Air Air Air Air Air Air Air Air Air )

[DEV] NG_Ting failed SafeWalk#1 +5
(Yaw: 34.706032
dX: 0.122812
dZ: 0.00
Blocks: Air Air Air Air Air Air Air Air Air )

[DEV] NG_Ting failed SafeWalk#1 +5
(Yaw: 33.806023
dX: 0.128046
dZ: 0.00
Blocks: Air Air Air Air Air Air Air Air Air )

**What is causing this false flag?**
1. Take a trident.
2. Enchant it with riptide.
3. Throw the trident.

**Is this false flag reproducible on the test server?**
maybe...

**Is there anything else to add?**
no

**Comment by MSWS** [comment]
Will look into this, thanks.

**Comment by NG-Ting** [comment]
I find that if I have effect jump_boost and slow_falling,there will be the above behavior.

If I don't have any effect, It report:
[DEV] NG_Ting failed Speed#2 +169 (Dist: 9.136098188907482 >= .7)
[DEV] NG_Ting failed Speed#4 +736 (Dist: 7.291090466691033 > 0.02500431987726535)
[DEV] NG_Ting failed Speed#2 +253 (Dist: 13.355071232381805 >= .7)
[DEV] NG_Ting failed Speed#4 +736 (Dist: 6.351709366299929 > 0.02500431987726535)
[DEV] NG_Ting failed Speed#2 +253 (Dist: 13.908474241309495 >= .7)
[DEV] NG_Ting failed Speed#4 +736 (Dist: 8.324713845079689 > 0.02500431987726535)
[DEV] NG_Ting failed Speed#2 +253 (Dist: 12.101354696085217 >= .7)

**Comment by MSWS** [comment]
These issues should all now be fixed. Will be pushed in 1.6.
