### ISSUE TITLE
Armor_stand problem

### ISSUE THREAD

**Issue by NG-Ting** [MSWS/NOPE#83]
**What server version are you running?**
Paper Spigot 1.15.2

**What version of NOPE are you running?**
1.5.4

**What is the bug?**
NOPE will cause the invisible armor_stand to appear

**Is there anything else to add?**
no

**Comment by MSWS** [comment]
Be more specific and give examples.

**Comment by NG-Ting** [comment]
run command ```/summon armor_stand ~ ~ ~ {Invisible:1b}```

Expect : summon an invisible armor_stand
Actually : armor_stand is invisible for few seconds, then appear!

**Comment by MSWS** [comment]
This should be fixed in the next 1.6 update.
