### ISSUE TITLE
Trigger don't work

### ISSUE THREAD

**Issue by NG-Ting** [MSWS/NOPE#84]
**What server version are you running?**
Paper Spigot 1.15.2

**What version of NOPE are you running?**
1.5.4

**What is the bug?**
Trigger don't work

**Is there anything else to add?**
Example :
1. run command ```/scoreboard objectives add test_1 trigger```
2. run command ```/scoreboard players enable @s test_1```
3. run command ```/trigger test_1 set 10```

Expect : scoreboard test_1 set to 10
Actually : It report => You cannot trigger this object yet

If I remove NOPE, trigger work well.

**Comment by MSWS** [comment]
Will look into.

**Comment by MSWS** [comment]
This has been fixed and will be patched in 1.6. Thanks for the detailed report!
