### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by MirceaDumitrescu** [MSWS/NOPE#85]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
1.15.2 Paper
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
1.6
**What is the bug?**
_Please be descriptive_
doesn't load, throws error: https://pastebin.com/NBSVgfD1
**Is there anything else to add?**
_Are there any error logs?_
https://pastebin.com/NBSVgfD1

**Comment by MSWS** [comment]
Should be fixed, please re-download the latest version from spigot.

**Comment by MirceaDumitrescu** [comment]
https://pastebin.com/GKG0HFrU

**Comment by MSWS** [comment]
Should *now* be fixed.
