### ISSUE TITLE
Climbing or falling in certain height

### ISSUE THREAD

**Issue by Arion12112** [MSWS/NOPE#86]
**What server version are you running?**
Paper 1.15.2

**What Minecraft Client Version are you running?**
java version 1.15.2

**What version of NOPE are you running?**
1.6.0.1

**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_

**Is there any debug information? (Please include average info if available)**
player failed fastclimb#1 + 15
player failed nofall#1 + 30 
played failed flight#1 +30
player failed selfharm#1 + 200

**What is causing this false flag?**
Climbing using scaffolding or jumping into water on certain height

**Is this false flag reproducible on the test server?**
yes

**Is there anything else to add?**

**Comment by MSWS** [comment]
Any range of this "certain height"?

**Comment by Arion12112** [comment]
maybe 128 blocks above im not so sure

**Comment by MSWS** [comment]
So you're climbing up a pillar of scaffolding over 128 blocks tall?

**Comment by Arion12112** [comment]
yeah thats right i make pillar of scaffolding 256 blocks tall, and i got this error on console, not sure if this linked
https://pastebin.com/eyYHCwzw

**Comment by MSWS** [comment]
> yeah thats right i make pillar of scaffolding 256 blocks tall, and i got this error on console, not sure if this linked
> https://pastebin.com/eyYHCwzw

Should be fixed in 1.6.1. I'll look into the other false flags.

**Comment by MSWS** [comment]
These should all be fixed in 1.6.1, thanks for reporting these.
