### ISSUE TITLE
False Flag when breaking mushroom blocks with an axe

### ISSUE THREAD

**Issue by BrakeZap** [MSWS/NOPE#87]
**What server version are you running?**
Version: 1.15.2 on Paper 
**What Minecraft Client Version are you running?**
1.15.2 Minecraft Client version
**What version of NOPE are you running?**
1.6.0.1
**What is the debug ID?**
FastBreak#1
**Is there any debug information? (Please include average info if available)**
Type: Red Mushroom Block
Time Diff: Ranges from -999 to -299
Hardness: .2 
**What is causing this false flag?**
Breaking a mushroom block with an enchanted stone axe with efficiency 1, unbreaking 1
**Is this false flag reproducible on the test server?**
Wasn't able to create an axe to test
**Is there anything else to add?**
Added to the violation amount very quickly and banned very quickly

**Comment by MSWS** [comment]
Will look into, thanks.

**Comment by MSWS** [comment]
Thanks for pointing this out, I forgot to add cocoa, mushroom blocks, jackolantern, pumpkin, vine, melon, and bee nest to the list of blocks that axes speed up. This should be fixed in 1.6.1.
