### ISSUE TITLE
Armor Stand Popping up with Animations OFF

### ISSUE THREAD

**Issue by anthonyxo110** [MSWS/NOPE#9]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_

Spigot

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_

1.14

**What is the bug?**
_Please be descriptive_

Armor Stand popping up when I have animations off

**Is there anything else to add?**

I have animations off, an armor stand keeps popping up with the killaura/reach alert. Having animations off is not disabling the armor stand. Thanks

**Comment by MSWS** [comment]
Does this bug still occur in 1.8 Minecraft?

**Comment by anthonyxo110** [comment]
Yes 1.8 minecraft. It spams chat with "you cannot use this here" if worldguard is blocking the flag use/break in that region.

**Comment by MSWS** [comment]
Does this happen no matter where you try to click? (Try moving around)

What happens if you run this command:

/minecraft:kill @e[type=ArmorStand,r=20]

**Comment by anthonyxo110** [comment]
Whenever you send off a killaura/reach alert while fighting another player an armor stand pops up in between the both of you. When this happens it breaks the hit detection for a second to two seconds.

Nothing?
