### ISSUE TITLE
False positive when hitting many mobs at once in a single area using sword

### ISSUE THREAD

**Issue by BrakeZap** [MSWS/NOPE#90]
**What server version are you running?**
Version: 1.15.2 on Paper 
**What Minecraft Client Version are you running?**
1.15.2 Minecraft Client version
**What version of NOPE are you running?**
1.6.0.1
**What is the debug ID?**
KillAura#1 mainly.  KillAura#5 and KillAura#4 rarely.
**Is there any debug information? (Please include average info if available)**
KillAura#1 Diff: Ranges: -.2 to .6.  
KillAura#4 Ent Dist: 2.86 Wall Dist: 2.36
KillAura#5 Hit invalid entity
**What is causing this false flag?**
When mobs are very close to each other and are hit with the Sweep attack, it triggers.
**Is this false flag reproducible on the test server?**
Wasn't able to create a sword to test.
**Is there anything else to add?**
For testing, mobs were placed in a 2x2 hole and hit rapidly using Sweep attacks.

**Comment by steviebeenz** [comment]
Having same issue with Sweeping Edge

**Comment by steviebeenz** [comment]
And mutliattack plugins

**Comment by MSWS** [comment]
Please create a separate false flag report for the multi-attack plugins. As for this issue it has been fixed and will be pushed in 1.6.1.
