### ISSUE TITLE
Small NoFall flag after ticking a cactus by jumping into it.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#91]
https://gyazo.com/525ffe048dc60e9f98dc93ad5ac7937a
**What server version are you running?**
Paper 1.15.2

**What Minecraft Client Version are you running?**
1.15.2
**What version of NOPE are you running?**
1.6 I think since it was on the test server.
**What is the debug ID?**
Can't find it, not perms
**Is there any debug information? (Please include average info if available)**
I don't know if I have perms for this on the test server.
**What is causing this false flag?**
Jumping into a cactus then landing on the ground.

**Is this false flag reproducible on the test server?**
Yes, found on the server.

**Is there anything else to add?**
I think this is fixable within the config although I am unsure. While someone getting banned from this is rare, I think it should be looked into.

**Comment by MSWS** [comment]
I will look into this, thanks.

**Comment by MSWS** [comment]
This will be fixed in 1.6.1.
