### ISSUE TITLE
Change rate that VL's go down over time in config

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#92]
**Is your feature request related to a problem/bug?**
No.
**Describe the solution you'd like**
I would like a way to change the rate that VL's decrease by over time in config.
**Have you tried implementing this solution alternatively?**
No, although I didn't see it in the config.

**Additional context**
None

**Comment by steviebeenz** [comment]
Having same issue

**Comment by MSWS** [comment]
I plan to add this, will update this issue when progress is started.

**Comment by MSWS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VL Decrementation configuration](https://trello.com/c/kQYjfvwZ/157-vl-decrementation-configuration)

**Comment by MSWS** [comment]
This has been added and will be released in 1.6.1.
