### ISSUE TITLE
More VL tweaks.

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#93]
**Is your feature request related to a problem/bug?**
No
**Describe the solution you'd like**
I would like the feature to see a user's current VL level for a flag in the guy (or a command). The feature to set a VL clear timer would also be nice.
**Have you tried implementing this solution alternatively?**
No.

**Additional context**
I might be able to implement something like this if I take my time though I am not the best with java.

**Comment by MSWS** [comment]
Not entirely sure what you mean by this. The current VL is available with %vl%, and /nope vl is a command you can use to view the person's VL levels.
