### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#94]
**Is your feature request related to a problem/bug?**

NOPE 

**Describe the solution you'd like**
 A Spicord or any other method bot framework allowing staff to query and view Violations etc. 

**Have you tried implementing this solution alternatively?**
_Either through the config or separate plugins_
Some features are possible with DiscordSRV

**Additional context**
Add any other context or screenshots about the recommendation please put here. This includes if the feature request involves a separate plugin, please make sure to link the plugin.

This also works for 1.15/1.16, powered by JDA and has a ton of lockin. OSS. 
[Spicord ](https://www.spigotmc.org/resources/spicord.64918/?__cf_chl_jschl_tk__=87980bc32bf793614e295ec101cebe86da64861e-1591947244-0-AfrlBptqi-QFFzpaXYlFJ1vDt4pBhlNcp_vlR_t44oijBMZl6H_azsgCM6RMCCdc2NYxf4v5b0Z0ReLUs0lTNZuckFMxrfvSa-IJo7gPJujk38-i7Zd92k9rVq7XTXOeJmbt27AXoph2bJwYjSM8mEF5E-IulOjwBlEAw5BWKW1kQubNtophG9Nd7c8MfRayyZlygPkUIbwz7hD9RSCcRMDeWEPYrqHVolgIen-w7lwLfwRaPy4fUhYfxdkhrq-J3XsXIAdK1VvPxRM2uGROONyWgIb-sYE92JYu-WA0xvgQbpS7wF4ELhSHjF0bIDTouw)

[Discord Bot API](https://www.spigotmc.org/resources/discord-bot-api-jda.49783/ )

DiscordSRV, the legendary plugin/api. Provides some lockin, OSS
[DiscordSRV](https://github.com/DiscordSRV/DiscordSRV )

Or my recommendation if you want no separate installs required for user... OSS
[The Core API, JDA](https://github.com/DV8FromTheWorld/JDA )

**Comment by MSWS** [comment]
This is out of the scope of NOPE and requires too much additional work to add. If a different developer wants to, NOPE has sufficient internal API and documentation to integrate it themselves.
