### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#97]
There are Two CI Sites that have great integration with Sonarcloud. These are [Travis](https://travis-ci.org/)  (free for public projects) and [Circle](https://circleci.com/)  (free-ish but recommended due to the fact that you can link to it as a download page).

These allow the coverage checks to run on your software. (I Think, I don't Understand Sonarcloud's coverage check). This is also helpful for the followings, it makes it work even better. 

I would also recommend setting up [Maven Analysis](https://sonarcloud.io/documentation/analysis/scan/sonarscanner-for-maven/) to allow for better Java scanning.

**Comment by MSWS** [comment]
NOPE at the moment does have any unit tests so I will not be adding this.
