### ISSUE TITLE
Auto Issue Labelling 

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#99]
If you wanted your issues to be automatically labelled an appropriate label, then I suggest [Issue Label Bot. ](https://github.com/marketplace/issue-label-bot). I use it on all my OSS Repos and it is amazing.

**Comment by MSWS** [comment]
I don’t want to inflate or unnecessarily add bots. NOPE doesn’t have that many labels nor does it receive that many PRs.
